-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Anamakine: 127.0.0.1:3306
-- Üretim Zamanı: 26 Oca 2025, 16:59:36
-- Sunucu sürümü: 9.1.0
-- PHP Sürümü: 8.2.26

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Veritabanı: `filmology`
--

-- --------------------------------------------------------

--
-- Tablo için tablo yapısı `categories`
--

DROP TABLE IF EXISTS `categories`;
CREATE TABLE IF NOT EXISTS `categories` (
  `Category_ID` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `Category` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  PRIMARY KEY (`Category_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Tablo döküm verisi `categories`
--

INSERT INTO `categories` (`Category_ID`, `Category`) VALUES
(1, 'Aksiyon'),
(2, 'Animasyon'),
(3, 'Bilim Kurgu'),
(4, 'Dram'),
(5, 'Fantastik'),
(6, 'Gerilim'),
(7, 'Komedi'),
(8, 'Korku'),
(9, 'Macera'),
(10, 'Romantik');

-- --------------------------------------------------------

--
-- Tablo için tablo yapısı `comments`
--

DROP TABLE IF EXISTS `comments`;
CREATE TABLE IF NOT EXISTS `comments` (
  `Comment_ID` int NOT NULL AUTO_INCREMENT,
  `Movie_ID` int DEFAULT NULL,
  `User_ID` int DEFAULT NULL,
  `Comment` varchar(10000) CHARACTER SET utf8mb4 COLLATE utf8mb4_german2_ci DEFAULT NULL,
  `C_Like` int DEFAULT NULL,
  `Dislike` int DEFAULT NULL,
  `Time` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`Comment_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_german2_ci;

--
-- Tablo döküm verisi `comments`
--

INSERT INTO `comments` (`Comment_ID`, `Movie_ID`, `User_ID`, `Comment`, `C_Like`, `Dislike`, `Time`) VALUES
(6, 108, 11, 'MERHABA', NULL, NULL, NULL);

-- --------------------------------------------------------

--
-- Tablo için tablo yapısı `failed_jobs`
--

DROP TABLE IF EXISTS `failed_jobs`;
CREATE TABLE IF NOT EXISTS `failed_jobs` (
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `connection` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `queue` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `payload` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `exception` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `failed_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `failed_jobs_uuid_unique` (`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Tablo için tablo yapısı `migrations`
--

DROP TABLE IF EXISTS `migrations`;
CREATE TABLE IF NOT EXISTS `migrations` (
  `id` int UNSIGNED NOT NULL AUTO_INCREMENT,
  `migration` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `batch` int NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Tablo döküm verisi `migrations`
--

INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES
(6, '2014_10_12_000000_create_users_table', 1),
(7, '2019_08_19_000000_create_failed_jobs_table', 1),
(8, '2019_12_14_000001_create_personal_access_tokens_table', 1),
(9, '2025_01_12_194402_categories', 1),
(10, '2025_01_12_194753_user_types', 1),
(11, '2025_01_14_134744_add_google_id_to_users_table', 2);

-- --------------------------------------------------------

--
-- Tablo için tablo yapısı `movies`
--

DROP TABLE IF EXISTS `movies`;
CREATE TABLE IF NOT EXISTS `movies` (
  `Movie_ID` int NOT NULL AUTO_INCREMENT,
  `Movie_Name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `Movie_Original_Name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `Movie_Story` varchar(5000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `Category` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `Director` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `Writer` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `Actor1` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `Actor2` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `Actor3` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `Actor4` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `Actor5` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `Movie_Release_Year` year DEFAULT NULL,
  `Movie_Duration` int DEFAULT NULL,
  `Movie_Cover_URL` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `Movie_Trailer_URL` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `IMDB_Point` float DEFAULT NULL,
  `View_Count` int DEFAULT NULL,
  PRIMARY KEY (`Movie_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=110 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Tablo döküm verisi `movies`
--

INSERT INTO `movies` (`Movie_ID`, `Movie_Name`, `Movie_Original_Name`, `Movie_Story`, `Category`, `Director`, `Writer`, `Actor1`, `Actor2`, `Actor3`, `Actor4`, `Actor5`, `Movie_Release_Year`, `Movie_Duration`, `Movie_Cover_URL`, `Movie_Trailer_URL`, `IMDB_Point`, `View_Count`) VALUES
(1, 'Ölümcül Sır', 'The Bricklayer', 'Deneyimli eski bir CIA ajanı olan Steve Vail, ajansın varlığını tehdit eden zorlu bir haraççıyla yüzleşmek için gölgelere geri çekilir. Vail\'in uzmanlığı ve kurnazlığı, gizli gündemler ve tehlikeli ittifaklar arasında gezinirken karmaşık bir entrika ağını çözerken test edilir. Riskler tırmanırken Vail, rakiplerini alt etmek, gerçek amaçlarını ortaya çıkarmak ve ulusal güvenliği tehlikeye atabilecek sırları korumak için içgüdülerine ve eğitimine güvenmelidir. Zaman tükenirken ve ajansın kaderi tehlikedeyken Vail, haraççıyı etkisiz hale getirmek ve düzeni sağlamak için tehlikeli bir göreve çıkar.', 'Aksiyon', 'Renny Harlin', 'Hanna Weg', 'Aaron Eckhart', 'Nina Dobrev', 'Clifton Collins Jr.', 'Tim Blake Nelson', 'Ilfenesh Hadera', '2023', 110, '001. the-bricklayer-2-27996.webp', 'https://www.youtube.com/watch?v=ayPesvG86gE', 5.2, 6),
(2, 'Boneyard', 'Cemitério', 'Polis Şefi Carter (Curtis \"50 Cent\" Jackson) on bir kadının kalıntılarını keşfettikten sonra, FBI Özel Ajanı Petrovick (Mel Gibson), kötü şöhretli \"mezarlık\" cinayetlerinden sorumlu seri katilin profilini çıkarmak için işe alınır. Polis gücü, narkotik ajansı ve FBI karşı karşıya gelirken, karmaşık bir entrika ağı herkesi bir şüpheliye dönüştürür.', 'Aksiyon', 'Asif Akbar', 'Asif Akbar', 'Mel Gibson', '50 Cent', 'Brian Van Holt', 'Nora Zehetner', 'Weston Cage', '2024', 96, '002. boneyard-cemiterio-73451.webp', 'https://www.youtube.com/watch?v=-bKxALUwJs8', 4.1, 10),
(3, 'Ferry 2', '', 'Ferry her şeyini kaybettikten sonra, Brabant\'tan uzakta, radarın altında bir hayat için emekli oldu. Yüzeysel temaslarla çevrili, iyi durumda gibi görünüyor. Ancak derinlerde, iç sesi onu rahatsız ediyor ve gerçek mutluluğu engelliyor. Ferry\'nin geçmişi şiddet, yalanlar ve ihanet izleriyle dolu. Düşük profilli kalmaya çalışırken vicdanıyla savaşıyor. Sert ama çekici uyuşturucu lordumuz neden son bir numara için emeklilikten çıksın ki..?', 'Aksiyon', 'Wannes Destoop', 'Piet Matthys', 'Frank Lammers', 'Aiko Beemsterboer', 'Tobias Kersloot', 'Marouane Meftah', 'Hamza Othman', '2024', 94, '003. ferry-2-56445.webp', 'https://www.youtube.com/watch?v=DQ3fSBus-HU', 5.6, 14),
(4, 'Ejderha Mızrağı: Güz Alacakaranlığının Ejderhaları', 'Dragonlance: Dragons of Autumn Twilight', 'Beş yıl ayrı kaldıktan sonra, gerçek tanrıların varlığına dair kanıt bulmak için Krynn dünyasını arayan bir grup maceracı, kanıtlarını mucizevi bir mavi kristal asa taşıyan barbar bir kadın şeklinde bulur. Kısa süre sonra, ejderhalardan oluşan bir ordu memleketlerini ele geçirince kendilerini savaşta bulurlar.', 'Aksiyon', 'Will Meugniot', 'Tracy Hickman', 'Michael Rosenbaum', 'Kiefer Sutherland', 'Lucy Lawless', 'Fred Tatasciore', 'Michelle Trachtenberg', '2008', 90, '004. ejderha-mizragi-guz-alacakaranliginin-ejderhalari-dragonlance-dragons-of-autumn-twilight-36957.webp', 'https://www.youtube.com/watch?v=O07-ARvtTjU', 4.8, 2),
(5, 'Yakın Düşmanlar', 'Enemies Closer', 'Orman bekçisi ve eski donanma SEAL\'i Henry, uyuşturucu karteli tarafından ABD-Kanada sınırında kaybolan büyük bir uyuşturucu sevkiyatını geri almaya zorlanır. Ormandayken, kendisine karşı kan davası olan bir adamla karşılaşır, ancak her iki adam da ormandan kaçmak ve karteli yenmek için mücadele etmelidir, birbirleriyle anlaşamaz ve bıçak sırtındadırlar.', 'Aksiyon', 'Peter Hyams', 'Eric Bromberg', 'Tom Everett Scott', 'Jean-Claude Van Damme', 'Orlando Jones', 'Linzey Cocker', 'Christopher Robbie', '2013', 85, '005. fullhd-enemies-closer-2013-film-izle.webp', 'https://www.youtube.com/watch?v=hW5z9QjgV-k', 5.1, 4),
(6, 'Tobin Köprüsü', 'Aftermath', 'Savaştan dönen ve travma sonrası stres bozukluğu yaşayan bir gazi, farkında olmadan Boston\'daki Tobin Anıt Köprüsü\'nde, eski askerlerden oluşan ve silahlı bir devrimci grubunun herkesi rehin alması sonucu, genç kız kardeşiyle birlikte sıkışıp kalır.', 'Aksiyon', 'Patrick Lussier', 'Nathan Graham Davis', 'Dylan Sprouse', 'Mason Gooding', 'Megan Stott', 'Dichen Lachman', 'Derek K. Moore', '2024', 97, '006. tobin-koprusu-aftermath-71167.webp', 'https://www.youtube.com/watch?v=Ds8JTI_9vjM', 5.1, 2),
(7, 'Kod Adı: Kırmızı', 'Red One', 'Noel Baba -- Kod Adı: Kırmızı -- kaçırıldıktan sonra, Kuzey Kutbu\'nun Güvenlik Şefi (Dwayne Johnson), Noel\'i kurtarmak için dünyanın en kötü şöhretli ödül avcısı ve kötü şöhretli bilgisayar korsanıyla (Chris Evans) birlikte dünyayı dolaşan, aksiyon dolu bir görevde yer almak zorundadır.', 'Aksiyon', 'Jake Kasdan', 'Chris Morgan', 'Dwayne Johnson', 'Chris Evans', 'Lucy Liu', 'J.K. Simmons', 'Bonnie Hunt', '2024', 123, '007. red-one-kod-adi-kirmizi-7121.webp', 'https://www.youtube.com/watch?v=7l3hfD74X-4', 6.4, 4),
(8, 'The Killer', '', 'Kinetik aksiyon gerilim filmi, Paris yeraltı dünyasında Ölüler Kraliçesi olarak bilinen ve korkulan gizemli ve kötü şöhretli bir suikastçı olan Zee\'yi konu alıyor. Ancak, karanlık akıl hocası ve yöneticisinin verdiği bir görev sırasında Zee, Paris\'teki bir gece kulübünde kör olmuş genç bir kadını öldürmeyi reddettiğinde, bu karar Zee\'nin ittifaklarını parçalayacak, kurnaz bir polis müfettişinin dikkatini çekecek ve onu kendi geçmişiyle çarpışma yoluna sokacak uğursuz bir suç komplosuna sürükleyecektir.', 'Aksiyon', 'John Woo', 'John Woo', 'Nathalie Emmanuel', 'Omar Sy', 'Sam Worthington', 'Diana Silvers', 'Saïd Taghmaoui', '2024', 126, '008. the-killer-5-5556.webp', 'https://www.youtube.com/watch?v=0sux_VLwQAc', 5.7, 4),
(9, 'Singham Again', '', 'Şu anda Keşmir\'de transfer edilen Bajirao Singham, Omar Hafiz olduğu ortaya çıkan bilinmeyen bir kimlik tarafından saldırıya uğrar. Ona tutuklanmasının son olmadığını ancak birisinin daha fazla kan banyosu ile intikamını sürdüreceğini söyler. Singham, Shiva ekibinin başına getirilir ve iki yıl sonra Omar\'ın tutuklanması sırasında ne demek istediğini sorgulamak zorunda kalır. Bir grup kaçakçı büyük bir uyuşturucu sevkiyatıyla tutuklanır ve bunun kimsenin görmediği ancak operasyonu üç adamın yönettiği Danger Lanka\'ya ait olduğunu ortaya çıkarır. Singham\'dan bir polis memuru olan Shakti Shetty, üç adamı kendi yetki alanında gördükleri için onları tutuklamakla görevlendirilir ancak tutuklamadan sonra Lanka polis karakolunu ateşe verdiğinde Shakti\'nin yokluğunda üç adam kaçar. Ramayana projesinde çalışan Singham\'ın karısı Avni, araştırması sırasında Lanka tarafından kaçırılır ancak bir polis memuru olan Satya onu kurtarır ve onun Aşramına götürür. Lanka, Aşram\'a ulaşır ve Avni\'yi vurarak yaralanır ve Lanka onu da yanına alır. Singham, Lanka\'nın gerçek kimliğini açıklamak için onu aradığı sırada, Lanka, Singham\'a, Avni\'nin yerini, eski üçlüyle hesaplaşmak isteyen polis arkadaşları Sooryavanshi ve Simmba ile birlikte Avni\'yi ondan kurtarmak için Singham\'ın yanına gelmesi şartıyla açıklayacağını söyler.', 'Aksiyon', 'Rohit Shetty', 'Vidhi Ghodgaonkar', 'Salman Khan', 'Deepika Padukone', 'Kareena Kapoor', 'Akshay Kumar', 'Ajay Devgn', '2024', 144, '009. singham-again-8964.webp', 'https://www.youtube.com/watch?v=MD7v0-igVIM', 5, 4),
(10, 'Dominique', '', 'İyi eğitimli bir suikastçı olan Dominique, Güney Amerika\'da yeni bir hayata başlamak için sorunlu geçmişinden kaçar. Ancak, Kolombiya\'da uçağını düşürdüğünde, kendini kısa sürede şiddet ve yolsuzlukla dolu bir kasabada bulur. Polis ve mafyanın acımasız saldırılarıyla karşı karşıya kalan Dominique, kendisini mi yoksa onu yanına alan masum bir aileyi mi koruyacağına karar vermelidir.', 'Aksiyon', 'Michael S. Ojeda', 'Michael S. Ojeda', 'Maurice Compte', 'Oksana Orlan', 'Chase Coleman', 'Ski Carr', 'Maria del Rosario Barreto', '2024', 100, '010. dominique-28031.webp', 'https://www.youtube.com/watch?v=YTOUqYkpaS4', 5.2, 2),
(11, 'Lego Marvel Avengers: Mission Demolition', '', 'Savaşlardan sonra, Hasar Kontrolü ortalığı temizler. Ancak bir kötü adam Avengers\'ı hedef aldığında, her şeyi kıran beceriksiz bir işçi olan beklenmedik bir kahraman, Dünya\'nın hayalini kurduğu kahraman olma ve Dünya Kahramanlarını kurtarma yolundaki tek umudu olabilir.', 'Animasyon', 'Ken Cunningham', 'Eugene Son', 'Will Friedle', 'Kevin Smith', 'David Kaye', 'John Stamos', 'Roger Craig Smith', '2024', 44, '011. lego-marvel-avengers-mission-demolition-75567.webp', 'https://www.youtube.com/watch?v=hqfL89ktaoY', 6.3, 2),
(12, 'Benim Uçan Dev Maceram', 'Una Aventura Gigante', 'Sebastian, Sophia ve Küçük Wawa, Nazca kültüründen gelen efsanevi yaratıkların yardımıyla kayıp ebeveynlerini bulmak için yola çıkarlar.', 'Animasyon', 'Eduardo Schuldt', 'Sandro Ventura', 'Reynaldo Arenas', 'Gustavo Bueno', 'Denisse Dibós', 'Yiddá Eslava', 'Merly Morello', '2023', 80, '012. benim-ucan-dev-maceram-una-aventura-gigante-88794.webp', 'https://www.youtube.com/watch?v=bU4RQlCAj7o', 6.9, 4),
(13, 'Çılgın Hırsız 4', 'Despicable Me 4', 'Gru ve Lucy, en yeni aile üyeleri Gru Jr.\'ı karşıladıkları için çok mutludurlar. Ancak, kurnaz Maxime Le Mal adlı yeni bir kötü adam ortaya çıktığında mutlulukları kısa sürer. Aileleri tehlikedeyken, Gru ve ekibi kötü adamı alt etmek ve sevdiklerini korumak için zekalarını ve becerilerini kullanmalıdır.', 'Animasyon', 'Chris Renaud', 'Mike White', 'Steve Carell', 'Pierre Coffin', 'Will Ferrell', 'Sofía Vergara', 'Chris Renaud', '2024', 94, '013. cilgin-hirsiz-4-despicable-me-4-2-66795.webp', 'https://www.youtube.com/watch?v=LtNYaH61dXY', 6.2, 0),
(14, 'Transformers: Başlangıç', 'Transformers One', 'Yeminli düşmanlar olarak bilinen, ama bir zamanlar kardeş gibi dost olan ve Cybertron\'un kaderini sonsuza dek değiştiren Optimus Prime ve Megatron\'un anlatılmamış köken hikayesi.', 'Animasyon', 'Josh Cooley', 'Eric Pearson', 'Chris Hemsworth', 'Brian Tyree Henry', 'Scarlett Johansson', 'Keegan-Michael Key', 'Steve Buscemi', '2024', 104, '014. transformers-baslangic-transformers-one-2-48220.webp', 'https://www.youtube.com/watch?v=0rmJXXKDrsM', 7.6, 0),
(15, 'Gürültü Ailesi: Casuslar İş Başında', 'No Time to Spy: A Loud House Movie', 'Lincoln ve Loud ailesi, yeni Gran-Gran\'ları Myrtle\'ı tropikal bir düğünle aileye katmaktan büyük mutluluk duyarlar; ancak Myrtle\'ın gizli ajan geçmişinden gelen eski bir düşmanı adaya geldiğinde şenlikler kısa kesilir.', 'Animasyon', 'Kyle Marshall', 'Whitney Wetta', 'Bentley Griffin', 'Alex Cazares', 'Piotr Michael', 'Brian Stepanek', 'Amy Sedaris', '2024', 81, '015. gurultu-ailesi-casuslar-is-basinda-no-time-to-spy-a-loud-house-movie-59035.webp', 'https://www.youtube.com/watch?v=3gPGMqXUFl0', 6.4, 0),
(16, 'Kaplanın Çırağı', 'The Tiger\'s Apprentice', 'Hikaye, San Francisco\'nun Çin Mahallesi\'nde birlikte yaşadığı eksantrik büyükannesinin anka kuşu yumurtasının koruyucusu olduğu ortaya çıktığında, istekleri dışında bu dünyaya çekilen normal bir çocuk olan Tom\'un etrafında dönüyor. Büyükannesi savaşta öldüğünde ve bir hayalet arabasıyla kaçırıldığında, Tom antik büyüyü öğrenmek ve yumurtanın yeni koruyucusu olmak için beklenmedik bir akıl hocası olan bir kaplan olan Bay Hu\'nun yanında çıraklık yapmak zorunda kalır. Her biri Çin burçlarının farklı bir işaretini temsil eden, doğuştan gelen hayvan özelliklerini korurken insan formuna dönüşebilen, beklenmedik bir egzotik yaratık grubuyla bir araya gelirler.', 'Animasyon', 'Raman Hui', 'David Magee', 'Henry Golding', 'Brandon Soo Hoo', 'Lucy Liu', 'Sandra Oh', 'Michelle Yeoh', '2024', 84, '016. kaplanin-ciragi-the-tiger-s-apprentice-28502.webp', 'https://www.youtube.com/watch?v=VgTc9zMQee8', 5.7, 0),
(17, 'Oyuncaklar Firarda', 'The Inseparables', '\"Toy Story\" filminin Oscar adayı senaristlerinin orijinal fikrinden uyarlanan THE INSEPARABLES, sınırsız hayal gücüne sahip kaçak bir kukla olan Don ile arkadaşa ihtiyaç duyan terk edilmiş bir oyuncak oyuncak olan DJ Doggy Dog\'un, Central Park\'ta yolları kesiştikten sonra New York\'ta dostluk dolu destansı bir maceraya atılmalarını konu alıyor.', 'Animasyon', 'Jérémie Degruson', 'Joel Cohen', 'Eric Judor', 'Jean-Pascal Zadi', 'Ana Girardot', 'Chris Marques', 'Laurence Huby', '2023', 90, '017. oyuncaklar-firarda-the-inseparables-20930.webp', 'https://www.youtube.com/watch?v=tZTJIs38f5M', 5.8, 0),
(18, 'Tombul Mombul Takımı: Sırt Sırta', 'Combat Wombat: Back 2 Back', 'Kötü bir teknoloji dehası, şehri bir metaverse simülasyonuna dönüştürmekle tehdit ediyor ve günü kurtarmak için Combat Wombat\'ı bırakıyor.', 'Animasyon', 'Ricard Cussó', 'Dominic Morris', 'Deborah Mailman', 'David Wenham', 'Ed Oxenbould', 'Mark Coles Smith', 'Elizabeth Cullen', '2023', 81, '018. tombul-mombul-takimi-sirt-sirta-combat-wombat-back-2-back-6274.webp', 'https://www.youtube.com/watch?v=Ps3Jra-3FfE', 5, 0),
(19, 'Cranston Academy: Monster Zone', '', 'Zeki 15 yaşındaki bir lise öğrencisi, beklenmedik bir şekilde yatılı okula transfer edilir ve burada başka bir boyuttan gelen canavarların bulunduğu bir portal açar.', 'Animasyon', 'Leopoldo Aguilar', 'Bob Barlen', 'Jamie Bell', 'Ruby Rose', 'Idzi Dulkiewicz', 'Ellie Piercy', 'Terry Mynott', '2020', 85, '019. kranston-akademi-canavar-bolgesi-cranston-academy-monster-zone-85445.webp', 'https://www.youtube.com/watch?v=C00bzB8GGyE', 5.1, 0),
(20, 'Ultraman: Rising', '', 'Ultraman unvanını taşıyan son kahraman olmak üzere Japonya\'ya dönen süperstar beyzbol oyuncusu Ken Sato. Ancak planları, en büyük düşmanının yavrusu olan yeni doğmuş bir Kaiju canavarını kendi çocuğu gibi büyütmek zorunda kaldığında ters gider. Sato ayrıca yabancılaştığı babasıyla olan ilişkisi ve Kaiju Savunma Gücü\'nün entrikalarıyla da uğraşmak zorunda kalacaktır.', 'Animasyon', 'Shannon Tindle', 'Shannon Tindle', 'Christopher Sean', 'Rob Fukuzaki', 'Hiro Nakamura', 'Gedde Watanabe', 'Tamlyn Tomita', '2024', 117, '020. ultraman-rising-9847.webp', 'https://www.youtube.com/watch?v=_YGosxAnZ4Q', 6.9, 0),
(21, 'Yapay Sevgilim', 'Robots', 'Charles bir kadın düşkünüyken Elaine bir altın avcısıdır. İkili, bir araya gelip kendilerinin robot kopyalarını kovalamak zorunda kaldıklarında insanlığı öğrenirler.', 'Bilim Kurgu', 'Casper Christensen', 'Robert Sheckley', 'Shailene Woodley', 'Jack Whitehall', 'Paul Rust', 'Nicholas Rutherford', 'Paul Jurewicz', '2023', 93, '021. robots-2-71465.webp', 'https://www.youtube.com/watch?v=5-QlB-CCozc', 5.5, 6),
(22, 'Yaratık: Romulus', 'Alien: Romulus', '2142\'de, Jackson kolonisinde, Rain Carradine, ebeveynlerinin ölümünden sonra onu korumak için babası tarafından yeniden programlanan sentetik \"kardeşi\" Andy ile birlikte yaşamaktadır. Koloniyi yöneten Weyland-Yutani Şirketi, kolonicileri Jackson\'da kalmaya zorlayarak madencilerin ve çiftçilerin sözleşmelerini uzatır ve onları köle gibi tutar. Rain\'in eski erkek arkadaşı Tyler\'ın sözleşmesi şirket tarafından uzatıldığında, Rain\'i gizlice hamile olan kız kardeşi Kay, kuzenleri Bjorn ve evlat edinilen kız kardeşi Navarro\'dan oluşan ekibine katılmaya ikna eder ve Yvaga gezegenine kaçmak için terk edilmiş bir istasyona giderler. Andy\'nin bilgisayar sistemiyle etkileşime girmesine ihtiyaçları vardır ve ayrıca Yvaga\'ya dokuz yıllık bir yolculuk için askıya alınmış animasyonun durağanlık odalarını kurtarmaları gerekir. İstasyona giderler ve Andy ile Bjorn, odaların yolculuk için kriyojenik yakıta ihtiyaç duyduğunu fark ederler. Andy ile birlikte giderler ve yanlışlıkla uzaylı yaratıkları serbest bırakırlar ve bölüm kilitlenir. Rain, hasarlı sentetik Rook\'un çipini kullanarak Andy\'nin istasyonun tüm işlevlerine erişebilmesini sağlar ancak Andy, Weyland-Yutani Şirketi\'ne sadık kalır ve Rain ikinci bir düzleme gönderilir. Ancak kısa süre sonra yaratıklar Rain\'in arkadaşlarından birine saldırır. Uzaylı yaratıklardan kurtulan biri olacak mı?', 'Bilim Kurgu', 'Fede Alvarez', 'Dan O\'Bannon', 'Cailee Spaeny', 'David Jonsson', 'Archie Renaux', 'Isabela Merced', 'Spike Fearn', '2024', 119, '022. alien-romulus-2-79752.webp', 'https://www.youtube.com/watch?v=GTNMt84KT0k', 7.1, 0),
(23, 'Our Man in L.A.', '', 'Uzaylı teknolojisi satıcısı, düşen bir UFO\'yu kurtarmaya çalışır.', 'Bilim Kurgu', 'Joshua Sowden', 'Guy Birtwhistle', 'Guy Birtwhistle', 'Brant Rotnem', 'Abigail Kate Thomas', 'Amy Motta', 'Krishna Smitha', '2024', 71, '023. our-man-in-la-20824.webp', 'https://www.youtube.com/watch?v=lHAu1857r8I', 4.5, 0),
(24, 'Omni Loop', '', 'Miami\'de fizikçi Zoya Lowe, göğsünde siyah bir delikle son evrededir. Sadece bir haftalık ömrü kalmıştır ve kocası Donald, kızı Jayne ve Jayne\'in nişanlısı Morris, son günlerini ailesiyle rahat bir şekilde geçirmesi için onu eve getirirler. Ancak Zoya, öleceğini gösteren kanamalar geçirdiğinde, banyoya gider ve on iki yaşındayken bulduğu gizemli bir hapı yutar ve hayatına beş gün geri döner. Şimdi Zoya, daha ileri nasıl dönebileceğini ve hayatında başka seçimler yapabileceğini araştırmak istemektedir. Mezun olan öğrenci Paula ile tanıştığında, hapı beş gün boyunca analiz etmek için onunla birlikte çalışır ancak hiçbir yere varamaz. Ancak daha sonra eski parlak üniversite arkadaşı Mark ve oğluyla tanışmak için Princeton\'a gittiğinde, hayatını gözden geçirir ve en iyi alternatifi bulduğu sonucuna varır.', 'Bilim Kurgu', 'Bernardo Britto', 'Bernardo Britto', 'Mary-Louise Parker', 'Ayo Edebiri', 'Carlos Jacott', 'Hannah Pearl Utt', 'Chris Witaske', '2024', 112, '024. omni-loop-49534.webp', 'https://www.youtube.com/watch?v=2URmAUEII9s', 5.5, 0),
(25, 'Isleen Pines', '', 'Bir grup arkadaş, yıllık Cadılar Bayramı partisi için bir araya gelirler; ancak gizemli ziyaretçiler tarafından rahatsız edilirler.', 'Bilim Kurgu', 'Matthew Festle', 'Matthew Festle', 'Naiia Lajoie', 'Darren Deng', 'Jackson Turner', 'Glenn Plummer', 'Jeremiah Benjamin', '2024', 84, '025. isleen-pines-12827.webp', 'https://www.youtube.com/watch?v=PDowwCEFGuw', 5.3, 0),
(26, 'Platform', 'El hoyo', 'Gizemli bir yer, tarif edilemez bir hapishane, derin bir çukur. Bilinmeyen sayıda kat. Her katta yaşayan iki mahkum. Hepsi için yiyecek içeren alçalan bir platform. Hayatta kalmak için insanlık dışı bir mücadele, ama aynı zamanda dayanışma için bir fırsat.', 'Bilim Kurgu', 'Galder Gaztelu-Urrutia', 'David Desola', 'Ivan Massagué', 'Zorion Eguileor', 'Antonia San Juan', 'Emilio Buale', 'Alexandra Masangkay', '2019', 94, '026. fullhd-the-platform-el-hoyo-izle.webp', 'https://www.youtube.com/watch?v=24Lf7fmKIXI', 7, 0),
(27, 'Maymunlar Cehennemi: Yeni Krallık', 'Kingdom of the Planet of the Apes', 'Yeni Maymunlar filmi, 2017\'deki Maymunlar Cehennemi Savaşı\'nın bitiminden yıllar sonra geçiyor. Birçok maymun topluluğu, Musa benzeri Sezar\'ın halkını bir vahaya getirmesinden bu yana büyüdü, insanlar ise vahşi benzeri bir varlığa indirgendi. Bazı maymun grupları Sezar\'ı hiç duymamışken, diğerleri onun öğretilerini çarpıtarak büyüyen imparatorluklar kurdular. Bu ortamda, bir maymun lideri insan teknolojisini bulmak için diğer grupları köleleştirmeye başlarken, klanının kaçırılmasını izleyen başka bir maymun özgürlük bulmak için bir yolculuğa çıkar. Genç bir insan kadın, kendi planları olmasına rağmen, ikincisinin arayışında kilit rol oynar.', 'Bilim Kurgu', 'Wes Ball', 'Josh Friedman', 'Owen Teague', 'Freya Allan', 'Kevin Durand', 'Peter Macon', 'William H. Macy', '2024', 145, '027. fullhd-maymunlar-cehennemi-yeni-krallik-fh-izle.webp', 'https://www.youtube.com/watch?v=XtFI7SNtVpY', 6.9, 0),
(28, 'Kesişen Dünyalar', 'Prityazhenie', 'Uzayda meydana gelen bir kazadan sonra bir uzay gemisi dünya atmosferine girer ve Rus savaş uçakları tarafından hasar görerek Moskova\'nın nüfuslu bir bölgesine çakılır ve kazada birkaç yüz insan hayatını kaybeder. Bir okul kızı uzaylılardan birinin hayatını kurtarır ve birlikte kendilerine zarar vermek isteyen insanlarla başa çıkmak zorundadırlar.', 'Bilim Kurgu', 'Fedor Bondarchuk', 'Oleg Malovichko', 'Irina Starshenbaum', 'Alexander Petrov', 'Rinal Mukhametov', 'Oleg Menshikov', 'Sergey Garmash', '2017', 132, '028. kesisen-dunyalar-24422.webp', 'https://www.youtube.com/watch?v=MCtKBMO8Sgc', 5.6, 0),
(29, 'Yang\'dan Sonra', 'After Yang', 'Genç kızının sevgili arkadaşı Yang adlı bir android arızalandığında, Jake onu onarmanın bir yolunu arar. Bu süreçte Jake, önünden geçen hayatı keşfeder ve karısı (Jodie Turner-Smith) ve kızıyla, varlığından haberdar olmadığı bir mesafeden yeniden bağlantı kurar.', 'Bilim Kurgu', 'Kogonada', 'Alexander Weinstein', 'Colin Farrell', 'Jodie Turner-Smith', 'Malea Emma Tjandrawidjaja', 'Justin H. Min', 'Orlagh Cassidy', '2021', 96, '029. yang-dan-sonra-after-yang-93672.webp', 'https://www.youtube.com/watch?v=Kwp32zLc08c', 6.6, 0),
(30, 'Büyük Felaket: Asit Yağmuru', 'Acide', 'Bir sıcak hava dalgasının ortasında, uğursuz bir bulut belirir ve onunla birlikte ölümcül bir asit yağmuru. Ayrılmış bir aile, dünyayı kasıp kavuran bu vebadan kurtulmak için bir araya gelmek zorunda kalacaktır.', 'Bilim Kurgu', 'Just Philippot', 'Yacine Badday', 'Guillaume Canet', 'Laetitia Dosch', 'Patience Munchenbach', 'Marie Jung', 'Martin Verset', '2023', 99, '030. buyuk-felaket-asit-yagmuru-acide-4219.webp', 'https://www.youtube.com/watch?v=6iZdUNKdM-E', 5.1, 0),
(31, 'Anne, Kalk!', 'Mother, Couch', 'Üç kardeş, annelerinin bir mobilya mağazasındaki koltuktan kalkmayı reddetmesi üzerine bir araya gelirler.', 'Dram', 'Niclas Larsson', 'Niclas Larsson', 'Ewan McGregor', 'Rhys Ifans', 'Taylor Russell', 'Ellen Burstyn', 'Lake Bell', '2023', 96, '031. mother-couch-anne-kalk-2320.webp', 'https://www.youtube.com/watch?v=Znu2_4vAD4s', 5.3, 0),
(32, 'Siyah Çay', 'Black Tea', 'Otuzlu yaşlarının başındaki genç bir Fildişi Sahili kadını olan Aya, düğün gününde herkesi şaşkına çevirerek hayır der. Çin\'e göç ettikten sonra, 45 yaşındaki Çinli bir adam olan Cai ile birlikte bir çay ihracatçısı dükkanında çalışır. Aya ve Cai aşık olur ancak ilişkileri geçmişlerinin karmaşasına ve diğer insanların önyargılarına rağmen hayatta kalabilir mi?', 'Dram', 'Abderrahmane Sissako', 'Kessen Tall', 'Nina Melo', 'Han Chang', 'Ke-Xi Wu', 'Michael Chang', 'Pei-Jen Yu', '2024', 110, '032. siyah-cay-black-tea-78358.webp', 'https://www.youtube.com/watch?v=xnW8ND9uuHk', 5.1, 2),
(33, 'My Penguin Friend', '', 'Gerçek bir destansı hikayeden esinlenerek, bir petrol sızıntısından kurtarıldıktan sonra kalbi kırık bir Brezilyalı balıkçının hayatını ve ruhunu değiştiren küçük bir kayıp penguen hakkındaki bu büyüleyici macera geliyor. Penguen ve balıkçı, uçsuz bucaksız okyanusun bile onları ayıramayacağı kadar bağlı oldukları beklenmedik arkadaşlar olurlar.', 'Dram', 'David Schurmann', 'Kristen Lazarian', 'Jean Reno', 'Adriana Barraza', 'Alexia Moyano', 'Nicolás Francella', 'Rochi Hernández', '2024', 97, '033. my-penguin-friend-9857.webp', 'https://www.youtube.com/watch?v=BE0kfDCiod0', 6.7, 0),
(34, 'Barış Çikolatası', 'Peace by Chocolate', 'Babasının çikolata fabrikasının bombalanmasının ardından, sevimli genç Suriyeli mülteci, hayalinin peşinden gitmek ve ailesinin mirasını korumak arasında sıkışıp kalarak yeni küçük kasaba hayatına uyum sağlamaya çalışır.', 'Dram', 'Jonathan Keijser', 'Jonathan Keijser', 'Hatem Ali', 'Ayham Abou Ammar', 'Yara Sabri', 'Mark Camacho', 'Najlaa Al Khamri', '2021', 96, '034. baris-cikolatasi-peace-by-chocolate-36343.webp', 'https://www.youtube.com/watch?v=WHkLYJT_0wM', 6.9, 0),
(35, 'Padu', '', '1977\'den bu yana katıldığı 20 Güneydoğu Asya Oyunları\'nda 13 altın madalya kazanan Malezya Kadın Basketbol Takımı\'nın güvenilirlik öyküsü.', 'Dram', 'Faisal Ishak', 'Umie Isa', 'Fify Azmi', 'Jojo Goh', 'Thanuja Ananthan', 'Mei Fen Lim', 'Mark Adam', '2024', 97, '035. padu-25133.webp', 'https://www.youtube.com/watch?v=4uNeIYrpb1A', 5.1, 0),
(36, 'Avustralya', 'Australia', 'İkinci Dünya Savaşı\'nın başlangıcında, Kuzey Avustralya\'da bir İngiliz aristokrat, Maryland büyüklüğünde bir sığır çiftliği miras alır. İngiliz sığır baronları onun topraklarını ele geçirmeyi planladığında, ülkenin en acımasız topraklarından yüzlerce mil boyunca 2.000 baş sığırı sürmek için isteksizce kaba bir çobanla güçlerini birleştirir, ancak yine de sadece birkaç ay önce Pearl Harbor\'a saldıran Japon kuvvetleri tarafından Darwin\'in bombalanmasıyla karşı karşıya kalır.', 'Dram', 'Baz Luhrmann', 'Stuart Beattie', 'Shea Adams', 'Eddie Baroo', 'Ray Barrett', 'Tony Barry', 'Jamal Sydney Bednarz', '2008', 165, '036. avustralya-australia-75185.webp', 'https://www.youtube.com/watch?v=M_PMKB5T4n4', 6.6, 0),
(37, 'Son Oyun', 'Wild Card', 'Nick Wild (Jason Statham), ölümcül mesleki becerilere ve kişisel bir kumar sorununa sahip bir Las Vegas korumasıdır. Bir arkadaşı sadist bir haydut tarafından dövüldüğünde, Nick karşılık verir, ancak haydutun güçlü bir mafya babasının oğlu olduğunu öğrenir. Birdenbire Nick, suçlu yeraltı dünyasına sürüklenir, infazcılar tarafından kovalanır ve mafya tarafından aranır. Bahisleri yükselten Nick, kaderini değiştirmek için son bir hamle yapar... ve bu sefer, her şey ya da hiçbir şey.', 'Dram', 'Simon West', 'William Goldman', 'Jason Statham', 'Michael Angarano', 'Dominik Garcia', 'Hope Davis', 'Milo Ventimiglia', '2015', 92, '037. son-oyun-wild-card-23275.webp', 'https://www.youtube.com/watch?v=7fJGbTfFPkM', 5.6, 0),
(38, 'Umudunu Kaybetme', 'The Pursuit of Happyness', 'Christopher Gardner adlı bir adamın gerçek hikayesinden uyarlanmıştır. Gardner, \"kemik yoğunluğu tarayıcısı\" olarak bilinen bir cihaza büyük yatırımlar yapmıştır. Bu cihazları satarak para kazandığını düşünmektedir. Ancak, çok daha yüksek bir fiyata x-ray\'den biraz daha iyi oldukları için iyi satmazlar. Gardner geçimini sağlamak için çalışırken, karısı onu terk eder ve dairesini kaybeder. Oğluyla birlikte sokakta yaşamaya zorlanan Gardner, kemik yoğunluğu tarayıcıları satmaya devam ederken aynı zamanda ücretli bir pozisyona terfi etme şansı düşük olan bir borsacı olarak ücretsiz staj yapar. Maaş alabilmesi için 6 aylık bir eğitimle rakiplerini geride bırakması ve ayakta kalabilmek için cihazlarını satması gerekir.', 'Dram', 'Gabriele Muccino', 'Steve Conrad', 'Will Smith', 'Jaden Smith', 'Thandiwe Newton', 'Brian Howe', 'James Karen', '2006', 117, '038. umudunu-kaybetme-the-pursuit-of-happyness-2-9238.webp', 'https://www.youtube.com/watch?v=89Kq8SDyvfg', 8, 0),
(39, 'Tek Gördüğüm Sensin', 'All I See Is You', 'Çocukluğundan beri, korkunç bir araba kazasında anne babasına ve görme yeteneğine mal olan kör güzel Gina, egzotik Bangkok\'taki evlerinden neredeyse hiç çıkmaz ve tamamen her şeyi olan, koruyucusu, rehberi ve dış dünyayla arasındaki tek aracı olan dikkatli ve şefkatli kocası James\'e güvenir. Ve sonra, beklenmedik bir şekilde, son teknoloji ürünü ancak oldukça deneysel bir kornea nakli Gina\'nın görüşünü, en azından sağ gözünü geri getirmeyi vaat eder ve aniden, keşfedilmemiş renkler ve duyularla dolu bir dünya önünde yavaş yavaş açılmaya başlar. Sonuç olarak, Gina kocasını ve aynadaki bilinmeyen yansımasını ilk kez görecektir, tuhaf ve benzeri görülmemiş bir güçlenme hissi yavaş yavaş onu ele geçirir. Ama, işler James\'in söylediği gibi mi? Ve hayat Gina\'nın hayal ettiği gibi olmadığında şimdi ne olacak?', 'Dram', 'Marc Forster', 'Sean Conway', 'Blake Lively', 'Jason Clarke', 'Ahna O\'Reilly', 'Miquel Fernández', 'Xavi Sánchez', '2016', 109, '039. fullhd-tek-gordugum-sensin-all-i-see-is-you.webp', 'https://www.youtube.com/watch?v=TudRyvs4YKg', 5.4, 0),
(40, 'Artık Çocuk Değiller', 'Boyz n the Hood', 'Yazar ve Yönetmen John Singleton\'ın, Kaliforniya\'nın Los Angeles şehrindeki sosyal sorunları tasviri, \"mahallede\" birlikte büyüyen üç arkadaşın hikayesini konu alıyor. Üvey kardeşler Doughboy (Ice Cube) ve Ricky Baker (Morris Chestnut), birbirlerinin kişiliklerinin zıttıdır ve karşılaştıkları zorlu hayatlara karşı çok farklı yaklaşımlar sunarlar. Ricky, USC\'ye futbol bursu kazanmayı uman ve spor yoluyla kurtuluşu arayan \"All-American\" atlettir; Doughboy ise çevresindeki şiddete, alkole ve suça yenik düşer, ancak güçlü bir gurur ve şeref duygusunu korur. Bu ikilinin arasında, kendisine doğru olanı yapmak ve her zaman eylemlerinin sorumluluğunu almak için karakter gücüne sahip olmayı öğretecek bir babaya, Furious Styles\'a (Laurence Fishburne) sahip olma şansına sahip olan arkadaşları Tre Styles (Cuba Gooding, Jr.) vardır.', 'Dram', 'John Singleton', 'John Singleton', 'Hudhail Al-Amir', 'Lloyd Avery II', 'Angela Bassett', 'Miya McGhee', 'Lexie Bigham', '1991', 112, '040. artik-cocuk-degiller-boyz-n-the-hood-28368.webp', 'https://www.youtube.com/watch?v=ZI-qlj-4cpk', 7.8, 0),
(41, 'Seven Cemeteries', '', 'Teksas\'ta, Meksika sınırındaki küçük bir kasabada, suç lordu Abuelo, Carmela ve Matteo\'ya ait olan çiftliği ister, ancak arazi yıllardır ailelerine aittir ve satmayı reddederler. Abuelo, Matteo\'yu bıçaklayarak öldürür ve Carmela\'ya çiftliği ona teslim etmesi için gün sonuna kadar vakti olduğunu söyler. Bu arada, yaşlı Santana Bravo, haksız yere suçlandıktan sonra yirmi sekiz yıl hapis yattıktan sonra denetimli serbestlikle hapisten çıkar ve Matteo\'yu ziyaret eder. Başına ne geldiğini öğrenir ve ansızın, yozlaşmış Şerif Jake yardımcılarıyla birlikte gelir ve Bravo\'yu idam eder. Bir cadı cesedini kulübesine getirir ve onu diriltir. Ayrıca, Bravo\'ya kanının ölüleri diriltebileceğini söyler. Bravo, Abuelo ve adamlarını yenmek ve Carmela ve çiftliğini korumak için eski arkadaşlarını geri getirmek üzere yedi mezarlığa gider. Bravo ve Abuelo arasındaki hesaplaşma başlayacaktır.', 'Fantastik', 'John Gulager', 'John Gulager', 'Danny Trejo', 'Maria Canals-Barrera', 'Efren Ramirez', 'Sol Rodriguez', 'Lew Temple', '2024', 84, '041. seven-cemeteries-49267.webp', 'https://www.youtube.com/watch?v=M_BtI82nMP8', 4.5, 2),
(42, 'Girl Haunts Boy', '', 'Bea, kasabaya yeni gelen çocuk Cole ile özel bir arkadaşlık kuran özgür ruhlu genç bir hayalettir ve 100 yıldır evinde yaşamaktadır. Cole\'un Bea\'yi görmesini sağlayan büyülü bir yüzük yardımıyla, hayatta olmanın anlamını yeniden keşfedeceklerdir, ancak aynı zamanda bırakmanın önemini de.', 'Fantastik', 'Emily Ting', 'Cesar Vitale', 'Peyton List', 'Michael Cimino', 'Andrea Navedo', 'Phoebe Holden', 'Brandon Micheal Hall', '2024', 100, '042. girl-haunts-boy-77612.webp', 'https://www.youtube.com/watch?v=QY0OcNIleNM', 6.3, 0),
(43, 'Kaos Yürüyüşü', 'Chaos Walking', 'Çok da uzak olmayan bir gelecekte, Todd Hewitt (Tom Holland), gezegenine çakılan gizemli bir kız olan Viola\'yı (Daisy Ridley) keşfeder. Burada tüm kadınlar kaybolmuş ve erkekler \"Gürültü\" tarafından etkilenmiştir - tüm düşüncelerini sergileyen bir güç. Bu tehlikeli manzarada, Viola\'nın hayatı tehdit altındadır - ve Todd onu korumaya yemin ederken, kendi iç gücünü keşfetmeli ve gezegenin karanlık sırlarını açığa çıkarmalıdır. The Bourne Identity ve Edge of Tomorrow\'un yönetmeninden ve en çok satan roman The Knife of Never Letting Go\'dan uyarlanan Chaos Walking\'de Daisy Ridley ve Tom Holland, Mads Mikkelsen, Demián Bichir, Cynthia Erivo, Nick Jonas, Kurt Sutter ve David Oyelowo ile birlikte rol alıyor.', 'Fantastik', 'Doug Liman', 'Patrick Ness', 'Tom Holland', 'Daisy Ridley', 'Demián Bichir', 'David Oyelowo', 'Kurt Sutter', '2021', 109, '043. kaos-yuruyusu-chaos-walking-79281.webp', 'https://www.youtube.com/watch?v=nRf4ZgzHoVw', 5.7, 0),
(44, 'Final Kızları', 'The Final Girls', 'Max (Taissa Farmiga) ve arkadaşları, Max\'in merhum annesinin (Malin Akerman) başrol oynadığı, 80\'lerin meşhur bir korku filminin anma gösterimine isteksizce katıldıklarında, yanlışlıkla kendilerini beyazperdede bulurlar. Kısa süre sonra kült klasik filmin içinde sıkışıp kaldıklarını fark ederler ve Max\'in utangaç çığlık kraliçesi olarak annesi de dahil olmak üzere kurgusal ve talihsiz \"Kan Banyo Kampı\" danışmanlarıyla birlikte filmin pala kullanan, maskeli katiliyle savaşmak zorunda kalırlar. Sahneler geçtikçe ceset sayısı artarken, bu filmden sağ kurtulup hayatta kalan FİNAL KIZLAR kim olacak?', 'Fantastik', 'Todd Strauss-Schulson', 'M.A. Fortin', 'Taissa Farmiga', 'Malin Akerman', 'Alexander Ludwig', 'Nina Dobrev', 'Alia Shawkat', '2015', 91, '044. the-final-girls-89665.webp', 'https://www.youtube.com/watch?v=zreNh78kTjg', 6.5, 0),
(45, 'Şeytanla anlaşma', 'The Covenant', 'Aynı cadılar meclisinin genç büyücüleri olan ve aynı sırrı paylaşan dört yakın arkadaş, birdenbire kendilerini, tıpkı kendileri gibi, 300 yıllık bir nefretin ardından meclislerini yok etmek için şehre gelen bir yabancıdan korumak zorunda kalırlar…', 'Fantastik', 'Renny Harlin', 'J.S. Cardone', 'Steven Strait', 'Laura Ramsey', 'Sebastian Stan', 'Taylor Kitsch', 'Chace Crawford', '2006', 97, '045. seytanla-anlasma-the-covenant-49813.webp', 'https://www.youtube.com/watch?v=dhOzQdG5y_k', 5.2, 0),
(46, 'Hayalet Avcıları: Ürperti', 'Ghostbusters: Frozen Empire', 'Hayalet Avcıları: Öteki Dünya (2021) filminde dünyayı yıkımın kadim tanrısından kurtardıktan sonra Gary ve Spenglers, orijinal Hayalet Avcıları\'nın (1984) dünyayı paranormal tehditlerden kurtarma yolculuğuna başladığı New York\'taki eski itfaiye istasyonuna yerleşirler. Ancak yeni buldukları huzurun tadını çıkarabileceklerini düşündükleri anda ekip, tarihin derinliklerinden durdurulamaz bir gücü serbest bırakan gizemli bir nesneye rastlar. Kaos hüküm sürerken ve saf kötülük dünyayı karanlığa sürüklerken, Hayalet Avcıları insanlığı kıyametin eşiğinden kurtarmak için bir kez daha öne çıkmalıdır. İki nesil hayalet avcısı yan yana savaşırken, riskler hiç olmadığı kadar yüksek. Her şey donmadan önce kaçınılmaz olanı önleyebilecekler mi?', 'Fantastik', 'Gil Kenan', 'Gil Kenan', 'Paul Rudd', 'Carrie Coon', 'Finn Wolfhard', 'Mckenna Grace', 'Kumail Nanjiani', '2024', 115, '046. hayalet-avcilari-urperti-ghostbusters-frozen-empire-7040.webp', 'https://www.youtube.com/watch?v=HpOBXh02rVc', 6.1, 0),
(47, 'Kara Hasat', 'Dark Harvest', 'Her sonbaharda, küçük bir Ortabatı kasabasında, \"Sawtooth Jack\" adlı doğaüstü bir hayalet mısır tarlalarından çıkar ve kasabanın kilisesine yaklaşır. Burada, genç oğlanlardan oluşan vahşi çeteler, yaşam ve ölümle ilgili yıllık hasat ayininde efsanevi kabusla yüzleşme şansını açgözlülükle beklemektedir. Richie Shepard, geçen yıl kasabadan çıkış biletini almak için \"Ekim Ödülü\"nü kazanan ağabeyinin gölgesinde yaşamaktadır. Kendini kanıtlamak ve ağabeyine katılmak için Richie, bu çıkmaz kasabadan kaçmak için her şeyi yapacak olan huzursuz hayalperest Kelly Haines ile birlik olur. Kurallara ve olasılıklara karşı, Richie ve Kelly, Koşu\'nu ve özgürlüklerini birlikte kazanmak için efsanevi kabusu avlamaya karar verirler.', 'Fantastik', 'David Slade', 'Michael Gilio', 'Casey Likes', 'Emyri Crutchfield', 'Dustin Ceithamer', 'Alejandro Akara', 'Ezra Buzzington', '2023', 96, '047. kara-hasat-dark-harvest-7108.webp', 'https://www.youtube.com/watch?v=Pge4NmBzdkE', 5.5, 0),
(48, 'Earwig', '', 'Avrupa\'nın bir yerinde, 20. yüzyılın ortalarında. Albert, buz gibi dişleri olan Mia adlı bir kıza bakmakla görevlendirilir. Mia, panjurların her zaman kapalı olduğu apartmanlarından hiç çıkmaz. Telefon düzenli olarak çalar ve Usta, Mia\'nın iyiliğini sorar. Ta ki Albert\'e çocuğu gitmeye hazırlaması gerektiği söylenene kadar.', 'Fantastik', 'Lucile Hadzihalilovic', 'Lucile Hadzihalilovic', 'Paul Hilton', 'Romane Hemelaers', 'Romola Garai', 'Alex Lawther', 'Peter Van den Begin', '2021', 114, '048. earwig-2-3004.webp', 'https://www.youtube.com/watch?v=bG6olibFw2U', 5.3, 0),
(49, 'Walking Against the Rain', '', '\"Walking Against the Rain\", birbirlerini bulmak için çaresizce çabalayan iki yabancı, Blair ve Tommy\'nin hikayesini anlatıyor. Tek iletişim biçimleri, yakında ölmek üzere olan iki pille çalışan radyo mikrofonu ve onları takip eden \'The Forsaken\' adlı yeni bir kötülük olan kayıpla yüzleşmeyi ve insanlığa olan güvenlerini yeniden keşfetmeyi öğrenmeleri gerekiyor.', 'Fantastik', 'Scott Lyus', 'Scott Lyus', 'Sophia Eleni', 'Reece Douglas', 'James Swanton', 'Diane Spencer', 'Johnny Vivash', '2022', 94, '049. walking-against-the-rain-94884.webp', 'https://www.youtube.com/watch?v=cL8cnQZEGMA', 4.2, 0),
(50, 'The New Boy', '', '1940\'lı yıllarda Avustralya\'da geçen \"The New Boy\", dokuz yaşında bir Aborjin yetim çocuğun (Reid) gece yarısı, asi bir rahibenin (Blanchett) yönettiği ücra bir manastıra gelmesinin ve varlığının hassas dengeler üzerine kurulu dünyayı altüst etmesinin hikayesini anlatıyor. Bu hikayede, manevi mücadele ve hayatta kalmanın bedeli anlatılıyor.', 'Fantastik', 'Warwick Thornton', 'Warwick Thornton', 'Aswan Reid', 'Cate Blanchett', 'Deborah Mailman', 'Wayne Blair', 'Shane Mckenzie Brady', '2023', 116, '050. the-new-boy-34089.webp', 'https://www.youtube.com/watch?v=hZ15NBAVOt0', 5.7, 0),
(51, 'Kalbim Senin', 'Haunted Heart', 'Alex, butik bir sahil restoranının ekibine katıldığında, gizemli restoran müdürü Max\'e aşık olmasıyla cinsel gerilimler yükselir. Duyguları tarafından kör edilen ilişki, yavaş yavaş yürek parçalayıcı bir hayatta kalma hikayesine dönüşür.', 'Gerilim', 'Fernando Trueba', 'Fernando Trueba', 'Matt Dillon', 'Aida Folch', 'Juan Pablo Urrego', 'Kika Georgiou', 'Polydoros Vogiatzis', '2024', 128, '051. haunted-heart-9938.webp', 'https://www.youtube.com/watch?v=QzFz0DgjLaI', 4.8, 3),
(52, 'Kuklacı', 'The Puppetman', 'Ölüm cezasına çarptırılmış mahkum bir katil olan Kuklacı her zaman masumiyetini ve kurbanlarını katlederken bedenini kontrol edenin kötü bir güç olduğunu savundu. Şimdi katilin kızı Michal, etrafındakiler vahşice ölmeye başladığında babasının iddiasında biraz doğruluk olabileceğinden şüphelenmeye başlar. Tüm sevdikleri öldürülmeden önce Kuklacı\'nın lanetini kırmaya çalışmalıdır.', 'Gerilim', 'Brandon Christensen', 'Brandon Christensen', 'Alyson Gorske', 'Angel Prater', 'Kio Cyr', 'Cameron Wong', 'Anna Telfer', '2023', 96, '052. kuklaci-the-puppetman-35835.webp', 'https://www.youtube.com/watch?v=Owv4PGJ6V0k', 5.3, 0),
(53, 'Gloria', '', 'Sevgilisi yüzünden hapis cezasına çarptırılan Gloria isimli orta yaşlı, sokaklarda büyüyen bir fahişe, çeteye karşı mücadele eder. Ancak Gloria, ailesi vurulduktan sonra istemeye istemeye de olsa altı yaşında, kendi iradesine sahip bir çocukla karşı karşıya gelir.', 'Gerilim', 'Sidney Lumet', 'John Cassavetes', 'Sharon Stone', 'Jean-Luke Figueroa', 'Jeremy Northam', 'Cathy Moriarty', 'George C. Scott', '1999', 108, '053. gloria-3-27099.webp', 'https://www.youtube.com/watch?v=WzJtmPAOb5o', 5.2, 0),
(54, 'The Front Room', '', 'Genç bir çiftin hayatı, adamın yabancılaşmış üvey annesini gönülsüzce kabul ettiklerinde altüst olur. Gerilim arttıkça, çiftin görünüşte normal evi paranoya ve korkunun savaş alanına dönüşür. Yaşlı kadının dengesiz davranışları ve gizemli geçmişi, çiftin ilişkisini çözmekle tehdit eden karanlık sırları açığa çıkarır. Evlerini ele geçiren uğursuz varlıkla boğuşurken, kendi şeytanlarıyla ve ön odada gizlenen şeyin ürkütücü gerçekliğiyle yüzleşmelidirler. Bu psikolojik gerilim filmi, aile, güven ve gerçeklik ile delilik arasındaki ince çizgi temalarını araştırıyor.', 'Gerilim', 'Max Eggers', 'Susan Hill', 'Brandy Norwood', 'Andrew Burnap', 'Kathryn Hunter', 'Neal Huff', 'David Manis', '2024', 94, '054. the-front-room-80612.webp', 'https://www.youtube.com/watch?v=sljURUzdRIs', 4.6, 0),
(55, 'Trapped in the Rocky Mountains', '', 'Boş bir kayak merkezinde istenmeyen bir buluşmaya çekilen eski üniversite arkadaşları, görünmeyen bir düşmanın hedefi haline gelince hayatta kalmak için mücadele eder ve uzun süredir saklı kalmış sırlar, iplerin kimin elinde olduğuna dair gerçeği ortaya çıkarabilir.', 'Gerilim', 'Patricia Frontain', 'Brandi Sperry', 'Aubrey Reynolds', 'Nick Puya', 'Steven Anthony Washington', 'Gina Su', 'Dan Hwang', '2024', 87, '055. trapped-in-the-rocky-mountains-97051.webp', 'https://www.youtube.com/watch?v=On9P4NJfBfs', 4.4, 0),
(56, 'Yalnız Öl', 'Die Alone', 'Dünya çapında doğanın yok edilmesinden sonra, intikam alır ve insanlar için ölümcül bir virüs serbest bırakır. Bir salgın çıkar ve genç Ethan ile doktor olan kız arkadaşı Emma, ​​şehirden kaçarak kendilerine ait olan gölün kenarındaki eve gelirler. Ethan yorgundur ve araba kullanırken uyur, arabalarını bir ağaca çarpar. Uyandığında Emma\'yı görmez ve onu arar. Orta yaşlı bir kadın olan Mae tarafından iki silahlı yabancıdan kurtarılır ve kadın onu evine getirir. Ethan hafızasını kaybetmiştir ve sağ ön kolu alçıdadır ancak Emma\'yı aramak ister. Günler boyunca, Emma\'ya ve kendisine ne olduğunu hatırlayana kadar hayatının parçalarını hatırlar.', 'Gerilim', 'Lowell Dean', 'Lowell Dean', 'Carrie-Anne Moss', 'Douglas Smith', 'Frank Grillo', 'Kimberly-Sue Murray', 'Jonathan Cherry', '2024', 91, '056. die-alone-65175.webp', 'https://www.youtube.com/watch?v=74IWGvodBCQ', 5.7, 77),
(57, 'The Stoic', '', 'Uyuşturucu çetesine baskın düzenledikten sonra bir grup paralı asker liderinin kırsal bir bölgede geri çekilmesini konu alıyor. Kaçakçıların kadim bir klanından olan \'Stoic\'in dikkatini çektikten sonra işler daha da kötüye gidiyor.', 'Gerilim', 'Jon Eckersley', 'Jon Eckersley', 'Scott Wright', 'Jarreau Benjamin', 'Stuart Brennan', 'Anka Evans', 'Tom Feasby', '2024', 96, '057. the-stoic-17617.webp', 'https://www.youtube.com/watch?v=d6uDcQbkQWI', 3.6, 0),
(58, 'Lazareth', '', 'Lee, yetim yeğenleri Imogen ve Maeve\'i kendi kendini yok eden bir dünyadan korur ve onları, bir yabancı onların huzurlu yaşamlarını tehdit edene kadar izole bir şekilde büyütür.', 'Gerilim', 'Alec Tibaldi', 'Alec Tibaldi', 'Ashley Judd', 'Sarah Pidgeon', 'Katie Douglas', 'Asher Angel', 'Edward Balaban', '2024', 86, '058. lazareth-73017.webp', 'https://www.youtube.com/watch?v=vIA3IGsuQjs', 4.3, 0),
(59, 'Previously Saved Version', '', '2200 yılında, Naoki ve Mayumi uzayda yüzen bir konutta yaşıyorlar. Naoki\'nin yıllar önce karısını mükemmel hayat versiyonunu yaşamak için bir androide dönüştürdüğü keşfedildiğinde, pastoral varoluşları sekteye uğrar.', 'Gerilim', 'Kei Ishikawa', 'Kei Ishikawa', 'Yûko Araki', 'Hideaki Itô', 'Nualpanod Nat Khianpukdee', 'Lalana Kongthoranin', 'James Laver', '2024', 117, '059. previously-saved-version-48428.webp', 'https://www.youtube.com/watch?v=eRtOuQdTJ6c', 5.5, 2),
(60, 'Demise', '', 'Latin peyzaj mimarı Caleb Castillo, çifte bir hayat sürmektedir. Yükselen moda yıldızı Fiona Hernandez ile ateşli bir ilişkiye girerken, aynı zamanda güzel karısı Celine\'e bağlıdır. Celine, dünyadaki her şeyden çok Caleb\'le bir çocuk sahibi olmak ister. Fiona\'nın sabrı, Caleb\'in karısını terk etme sözleriyle tükenirken, Celine, Caleb\'in sadakatsizliğini keşfeder; ayrılırlar. Caleb ve Fiona birlikte yeni bir hayat kurmaya başlarlar, ancak Celine, Caleb\'in yeni doğan oğlu Brody de dahil olmak üzere, hakkı olduğuna inandığı şeyleri geri almaya takıntılı hale gelir. Görünüşe göre başarılı olabilir. Ancak Celine, sinsi hedeflerine ulaştığını düşündüğü anda.', 'Gerilim', 'Yara Estrada Lowe', 'Yara Estrada Lowe', 'Liz Fenning', 'Carlo Mendez', 'Crystal Hernandez', 'Richard Rivera', 'Morris Jude', '2024', 135, '060. demise-6585.webp', 'https://www.youtube.com/watch?v=7yY_HpJm9ls', 4.2, 0),
(61, 'Cumartesi Gecesi', 'Saturday Night', '11 Ekim 1975\'te saat 23:30\'da, genç komedyenler ve yazarlardan oluşan vahşi bir topluluk televizyonu ve kültürü sonsuza dek değiştirdi. \"Saturday Night\", Saturday Night Live\'ın ilk yayınından önceki 90 dakika boyunca sahne arkasında yaşananların gerçek hikayesine dayanıyor. Mizah, kaos ve neredeyse gerçekleşmeyecek bir devrimin büyüsüyle dolu, o ünlü sözler ilk kez dile getirilene kadar dakikaları gerçek zamanlı olarak geri sayın.', 'Komedi', 'Jason Reitman', 'Gil Kenan', 'Gabriel LaBelle', 'Rachel Sennott', 'Cory Michael Smith', 'Ella Hunt', 'Dylan O\'Brien', '2024', 109, '061. saturday-night-9270.webp', 'https://www.youtube.com/watch?v=iZ9O_tl5Npk', 7, 0),
(62, 'Tatil Fiyaskosu', 'Disaster Holiday', 'Baba egzotik bir tatil sözü verir ama yanlışlıkla Zanzibar yerine Durban\'ı rezerve eder. Ailenin hayalindeki tatil neşeye dönüşürken, baba terfi almak için çabalarken kaos çıkar.', 'Komedi', 'Rethabile Ramaphakela', 'Rethabile Ramaphakela', 'Jacques Adriaanse', 'Tina Jaxa', 'Lunathi Mampofu', 'Kenneth Nkosi', '', '2024', 93, '062. fullhd-tatil-fiyaskosu-disaster-holiday.webp', 'https://www.youtube.com/watch?v=6LzcJW6XBlQ', 4.8, 0),
(63, 'Gelecek Yıl Aynı Yerde', 'This Time Next Year', 'Minnie ve Quinn aynı gün, bir dakika arayla doğarlar. Hayatları birlikte başlayabilir, ancak dünyaları birbirinden daha farklı olamazdı. Yıllar sonra kendilerini tekrar birlikte bulurlar. Belki de aşka bir şans vermenin zamanı gelmiştir.', 'Komedi', 'Nick Moore', 'Sophie Cousens', 'Sophie Cookson', 'Lucien Laviscount', 'Golda Rosheuvel', 'Monica Dolan', 'John Hannah', '2024', 116, '063. gelecek-yil-ayni-yerde-this-time-next-year-51922.webp', 'https://www.youtube.com/watch?v=C92Z4D85Lfk', 5.6, 0),
(64, 'Stinky Summer', '', 'Olivia ve arkadaşlarıyla birlikte sevimli bir kokarcanın Camp Clover\'da çılgın bir yaz macerasına katılın ve uluslararası casusların Olivia\'nın babasının gizli icadını çalmasını engellemeye çalışın.', 'Komedi', 'Amanda Raymond', 'Jenna St. John', 'Francesca Capaldi', 'Oakley Bull', 'Helen Day', 'Daniel Ross', 'Stella Glorioso', '2024', 90, '064. stinky-summer-5484.webp', 'https://www.youtube.com/watch?v=4owztVpMtng', 6.4, 0),
(65, 'I\'ll Be Right There', '', 'Wanda hayatındaki herkesle ilgilenmek istiyor. Kendine ayıracak vakti neredeyse yok, zaten ne yapacağını da bilmiyor.', 'Komedi', 'Brendan Walsh', 'Jim Beggarly', 'Edie Falco', 'Jeannie Berlin', 'Kayli Carter', 'Charlie Tahan', 'Bradley Whitford', '2023', 98, '065. hemen-orada-olacagim-i-ll-be-right-there-86416.webp', 'https://www.youtube.com/watch?v=v92tjMK7e2c', 5.7, 0),
(66, 'Summer Camp', '', 'Nora, Ginny ve Mary, çocukluktan beri birlikte olan ve her yaz bir yaz kampında birlikte vakit geçiren üç yakın arkadaşın hikayesini konu alıyor. Yıllar sonra, bir yaz kampı buluşması için tekrar bir araya gelme fırsatı ortaya çıktığında, hepsi bunu değerlendirir.', 'Komedi', 'Castille Landon', 'Castille Landon', 'Diane Keaton', 'Kathy Bates', 'Alfre Woodard', 'Eugene Levy', 'Dennis Haysbert', '2024', 95, '066. summer-camp-71968.webp', 'https://www.youtube.com/watch?v=mTKePgJ9r0E', 4.4, 0),
(67, 'The Mick and the Trick', '', 'Kübalı bir suç patronu ve IRA için çalışan İrlandalı bir tetikçi kurtulmak istiyor. Ancak ne Kübalı suç patronu ne de IRA buna izin veremez. Çok fazla şey biliyor. Ancak çok hareketli ve becerikli bir sokak fahişesinin yardımıyla tetikçinin kurtulma şansı daha da arttı.', 'Komedi', 'Tom DeNucci', 'Ozz Gomez', 'Peter Greene', 'Federico Castelluccio', 'Richard Kline', 'John Fiore', 'Darlene Tejeiro', '2024', 96, '067. the-mick-and-the-trick-78333.webp', 'https://www.youtube.com/watch?v=7H-UB6Yf754', 4.6, 0),
(68, 'Bookworm', '', '11 yaşındaki Mildred\'in dünyası, artık kendisinden ayrı yaşayan ve artık bir sihirbaz olmayan babası Strawn Wise\'ın ona bakmaya gelmesi ve onu Canterbury Panteri olarak bilinen mitolojik bir canavarı bulmak için kamp yapmaya götürmeyi kabul etmesiyle altüst olur.', 'Komedi', 'Ant Timpson', 'Toby Harvard', 'Nell Fisher', 'Morgana O\'Reilly', 'Millen Baird', 'Elijah Wood', 'Nikki Si\'ulepa', '2024', 103, '068. bookworm-42125.webp', 'https://www.youtube.com/watch?v=WLjVWIxwpao', 6.1, 0),
(69, 'Adamım Benim!', 'I Love You, Man', 'Peter Klaven\'ın dünyası emlak işi ve nişanlısı olacak Zooey etrafında döner. Peter evlenme teklif ettikten sonra, Zooey en yakın arkadaşlarını arar ve düğün planlama moduna geçerler. Peter\'ın hiç erkek arkadaşı yoktur ve bu da sorunlara yol açar: Yapışkan bir adam mı olacak ve sağdıcı kim olacak? Zooey, arkadaşları ve Peter\'ın kardeşi Robbie, garip anlara yol açan yardım teklif ederler. Sonra, Peter\'ın ev sahipliği yaptığı bir açık evde, sevimli, mütevazı bir adam olan Sydney ile tanışır. Kartvizitlerini takas ederler ve Peter onu içki içmek için arar. Başta harika olan ancak daha sonra Peter\'ın nişanını ve kariyerini tehdit eden bir arkadaşlık gelişir. Erkekler arkadaş olabilir ve çiftler aşık olabilir mi?', 'Komedi', 'John Hamburg', 'John Hamburg', 'Paul Rudd', 'Rashida Jones', 'Sarah Burns', 'Greg Levine', 'Jaime Pressly', '2009', 105, '069. fullhd-adamim-benim-turkce-dublaj-full-hd-izle.webp', 'https://www.youtube.com/watch?v=TJU061IOMMU', 7, 0),
(70, 'İkinci Şanslar', 'Second Chances', 'Eski bir çantada bulunan yırtılmış bir aşk notu, bir ikinci el mağazası çalışanını, kendi aşık olduğu kişiyle başa çıkmaya çalışırken bir çifti yeniden bir araya getirmek için gizli bir göreve gönderir.', 'Komedi', 'Rick Walker', 'Jacie Quillen', 'Allyson Cristofaro', 'Thesa Loving', 'Paige Kriet', 'Weston Vrooman', 'Jennifer Ferguson', '2022', 80, '070. ikinci-sanslar-second-chances-29853.webp', 'https://www.youtube.com/watch?v=jBENBTu595Q', 5.7, 0),
(71, 'Tenants', '', 'Tanıdık olmayan bir apartman kompleksinde uyanan bir kadın, gölgeli bir figür tarafından avlanırken çaresizce kız kardeşini arar. Binada ilerlerken, etkileşime girdiği kiracıları tarifsiz dehşetler bekler.', 'Korku', 'Jonathan Louis Lewis', 'Sean Mesler', 'Mary O\'Neil', 'Rib Hillis', 'Douglas Vermeeren', 'Clarke Wolfe', 'Myles Cranford', '2024', 94, '071. tenants-5525.webp', 'https://www.youtube.com/watch?v=j6Bgxgej1M8', 5.9, 0),
(72, 'Souls of the Damned', '', 'Bir grup cadı, korkunç kabuslar aracılığıyla bir adamın acılarından güç kazanır.', 'Korku', 'Frank Palangi', 'Frank Palangi', 'Elissa Ebersold', 'Shelley Fairbanks', 'Lisa Grace', 'Erica James', 'Kelly Kohn', '2024', 57, '072. souls-of-the-damned-9397.webp', 'https://www.youtube.com/watch?v=4wHgR8ucDro', 6, 0),
(73, 'İçimdeki Şeytan', 'The Devil Inside', 'Amerikalı bir kız olan Isabella, üç din adamını öldüren annesinin başına ne geldiğini anlamak için bir belgesel yapmaya koyulur. Akıl hastalığı nedeniyle mahkum edilmemiştir ve İtalya\'daki bir akıl hastanesine gönderilmiştir. Isabella, İtalya\'da annesinin durumunun tıbbi olmayabileceğini, ancak insan dışı bir ele geçirilme olabileceğini açıklayan bazı rahiplerle görüşür.', 'Korku', 'William Brent Bell', 'William Brent Bell', 'Fernanda Andrade', 'Simon Quarterman', 'Evan Helmuth', 'Ionut Grama', 'Suzan Crowley', '2012', 83, '073. fullhd-aimdeki-eytan-a-the-devil-inside-2012-720p.webp', 'https://www.youtube.com/watch?v=uWPGSbHlI2w', 4.2, 0);
INSERT INTO `movies` (`Movie_ID`, `Movie_Name`, `Movie_Original_Name`, `Movie_Story`, `Category`, `Director`, `Writer`, `Actor1`, `Actor2`, `Actor3`, `Actor4`, `Actor5`, `Movie_Release_Year`, `Movie_Duration`, `Movie_Cover_URL`, `Movie_Trailer_URL`, `IMDB_Point`, `View_Count`) VALUES
(74, 'Temurun', '', 'Kardeşler Dewi ve Sena, ebeveynlerinin gidişinin ardından yas tutmaktadır. Dewi ve Sena\'nın hissettiği ve üstesinden gelmeye çalıştığı kederin ortasında, ikisi de geride bıraktıkları miras karşısında şok olmuşlardır. Ailenin atalarından kalan bir miras, Dewi ve Sena\'nın hayatlarını değiştiren bir dehşet getirir. Çeşitli korkutucu mistik olaylar ve mantıksız dehşet, ikisinin başına gelmeye başlar. Dewi ve Sena parayı sevmese ve bu mirası umsalar da, yapılabilecek hiçbir şey yoktur. İkisi de atalarının mirasını kabul etmeye ve onunla yan yana yaşamaya devam etmeye çalışırlar. Peki Dewi ve Sena\'nın nesilden nesile miras olarak bıraktığı miras tam olarak nedir? Aileden kalan ve korkunç dehşete yol açan mirasın ardındaki tüm gizemleri aşabilir ve ortaya çıkarabilirler mi?', 'Korku', 'Inarah Syarafina', 'Vontian Suwandi', 'Yasamin Jasem', 'Bryan Domani', 'Karina Suwandhi', 'Jajang C. Noer', 'Kiki Narendra', '2024', 85, '074. temurun-88255.webp', 'https://www.youtube.com/watch?v=6QGYK9icpJo', 4.6, 0),
(75, 'Stream', '', 'Roy ve Elaine Keenan ailelerinin dağıldığını fark ettiğinde, bir şeyler yapılması gerektiğine karar verirler. Roy işini ikinci plana atar ve geçmişlerinden bir tatili yeniden yaratma fırsatını yakalarlar. Şirin bir otelde huzurlu bir konaklama tam da ihtiyaç duydukları şeydir, ancak onları bekleyen şey bu değildir. Görünüşte sıradan koridorlarda devriye gezen dört deli katille, olasılıklar kesinlikle Keenan ailesinin lehine değildir. Roy, basit hafta sonu kaçamakları gerçekten de ölmeye değer bir tatile dönüşürken kendi hayatı ve ailesinin hayatı için savaşmalıdır.', 'Korku', 'Michael Leavy', 'Steven Della Salla', 'Jeffrey Combs', 'Charles Edwin Powell', 'Danielle Harris', 'Wesley Holloway', 'Sydney Malakeh', '2024', 123, '075. stream-2-98222.webp', 'https://www.youtube.com/watch?v=g26DsFt2snY', 5.5, 0),
(76, 'Lord of Wolves', '', 'Ev arkadaşı gizemli koşullar altında öldüğünde, Nic Cross olay yerinde bırakılan gizemli piramit şeklindeki bir aleti miras alır ve farkında olmadan Londra\'nın karanlık alt tarafında yaşayan bir kurt-insan tarikatını çağırır. Nic\'in yolu üç sorunlu yabancıyla kesiştiğinde, canavar sürüsünden birine dönüşmeden önce Kurtların Efendisi\'ni yenmek için birleşmeleri gerekir.', 'Korku', 'Charlie Steeds', 'Charlie Steeds', 'Joshua Tonks', 'Jake Watkins', 'Rosie Edwards', 'Michaela Longden', 'Jon Holmes', '2024', 87, '076. lord-of-wolves-8249.webp', 'https://www.youtube.com/watch?v=AZoFHwjXflQ', 3.4, 0),
(77, 'Out of Darkness', '', 'Eski Taş Çağı\'nda, farklı erken dönem insanlarından oluşan bir çete, yeni bir toprak arayışında bir araya gelir. Ancak kötü niyetli, mistik bir varlığın onları avladığından şüphelendiklerinde, klan hiç öngöremedikleri bir tehlikeyle yüzleşmek zorunda kalır.', 'Korku', 'Andrew Cumming', 'Ruth Greenberg', 'Iola Evans', 'Arno Lüning', 'Rosebud Melarkey', 'Tyrell Mhlanga', 'Chuku Modu', '2022', 88, '077. out-of-darkness-91360.webp', 'https://www.youtube.com/watch?v=sU_SQo1wbos', 5.5, 0),
(78, 'Beyaz Köpekbalığı', 'Great White', 'Küçük deniz uçağı işletmelerini ayakta tutmak için mücadele eden emekli bir deniz biyoloğu ve köpekbalığı ısırığı kurtulanı olan Charlie, kız arkadaşı Kaz ve arkadaşı Benny, yüksekten uçan tatilciler Joji ve eşi Michelle tarafından görevlendirildiklerinde çok sevinirler. Ancak, deniz uçağı uzak Hell\'s Reef\'in kumlu bir plajına iner inmez felaket yaşanır ve ekip kendilerini sınırlı malzemelerle donatılmış, dayanıksız bir şişme cankurtaran botunda sıkışmış halde bulur. Şimdi, talihsiz mürettebat uçsuz bucaksız okyanusun karanlık, derin sularında amaçsızca sürüklenmektedir ve yalnız değillerdir: devasa, gizli bir büyük beyaz köpekbalığı çoktan kokularını almıştır ve beslenmek için hiçbir şeyden çekinmeyecektir. En üst düzey okyanus yırtıcısının güçlü çenelerinden kaçabilecekler midir?', 'Korku', 'Martin Wilson', 'Michael Boughen', 'Katrina Bowden', 'Aaron Jakubenko', 'Kimie Tsukakoshi', 'Tim Kano', 'Te Kohe Tuhaka', '2021', 91, '078. great-white-5091.webp', 'https://www.youtube.com/watch?v=V67sjW5eyJU', 4.2, 0),
(79, 'Dehşetin Dişleri', 'The Reef', 'Luke, Londra\'dan gelen arkadaşı Matt ve kız arkadaşı Suzie\'yi ve kendisiyle ve denizci Warren\'la birlikte yelken açmak için Sidney\'den gelen Matt\'in kız kardeşi ve Luke\'un eski kız arkadaşı Kate\'i karşılar. Ancak, tekne su altındaki bir kayaya çarpar ve alt kısmında bir açıklık olacak şekilde alabora olur. Luke, tekneyi karaya ters yönde hareket ettiren bir akıntı olduğu için güçlerinin yettiği kadar kuzey yönünde yüzmeleri gerektiğini söyler ancak Warren, suda köpekbalıkları olduğu için yardım beklemek üzere teknenin gövdesinde kalmayı tercih eder. Dörtlü yüzer ancak büyük beyaz bir köpekbalığı tarafından avlanırlar.', 'Korku', 'Andrew Traucki', 'Andrew Traucki', 'Damian Walshe-Howling', 'Gyton Grantley', 'Adrienne Pickering', 'Zoe Naylor', 'Kieran Darcy-Smith', '2010', 94, '079. fullhd-the-reef.webp', 'https://www.youtube.com/watch?v=0UD2gbjB3vw', 5.8, 0),
(80, 'Ölüm gecesi', 'Fear the Night', 'Kaliforniya tepelerinde saklı, tenha bir çiftlik evinde, sekiz kadın bir bekarlığa veda partisini kutlamak için bir araya gelir. Maskeli davetsiz misafirler aniden üzerlerine çullanıp hem evi hem de sakinlerini hedef alan bir ok yağmuru başlattığında, neşeli anları karanlık bir hal alır. Bu korkunç saldırıyla karşı karşıya kalan konuklar arasında bulunan bir askeri gazi olan Tess, kadınları cesur bir son direnişte bir araya getirmek için öne çıkar. Birlikte, hayatlarını korumaya ve o korkunç geceye katlanmaya kararlı bir şekilde geri savaşmalıdırlar.', 'Korku', 'Neil LaBute', 'Neil LaBute', 'Maggie Q', 'Kat Foster', 'Travis Hammer', 'Gia Crovatin', 'Brenda Meaney', '2023', 92, '080. fear-the-night-15502.webp', 'https://www.youtube.com/watch?v=1QZNSrMTBSM', 4.8, 0),
(81, 'The Star City Murders', '', 'Bir dedektif ekibi, kolluk kuvvetlerinin daha önce hiç görmediği yöntemlere sahip bir seri katilin peşine düşer.', 'Macera', 'Giles Andrews', 'Giles Andrews', 'Heath Centazzo', 'Tim Russ', 'Michelle Lukes', 'Amy Motta', 'Jason Graham', '2024', 79, '081. the-star-city-murders-97187.webp', 'https://www.youtube.com/watch?v=_pJrDkbJ8wU', 4.6, 0),
(82, 'Lost in Florence', '', 'Eric Lombard bir yol ayrımındadır - profesyonel futbol oynama gibi uzun vadeli hayalini sürdürmeye devam mı edecektir yoksa hayatının bir sonraki aşamasına geçip hukuk fakültesine mi başvuracaktır? Bu kararla boğuşurken Eric - uzun zamandır birlikte olduğu kız arkadaşı Colleen ile birlikte - Floransa\'daki kuzenini ziyaret eder. Orada, şaşkınlıkla, yerel bir spor olan Calcio Storico ile tanışır - ve Eric\'in hayatı hakkında varsaydığı her şey sorgulanır.', 'Macera', 'Evan Oppenheimer', 'Evan Oppenheimer', 'Brett Dalton', 'Stana Katic', 'Alessandra Mastronardi', 'Alessandro Preziosi', 'Marco Bonini', '2017', 97, '082. lost-in-florence-4268.webp', 'https://www.youtube.com/watch?v=DoYz_EAdU1g', 5.1, 0),
(83, 'Journey to the Forbidden Valley', '', 'Küçük bir uçağın Orta Çin\'in ücra bir bölgesine çakılmasının ardından, Çinli bir çocuk ve Amerikalı koruyucusu da dahil olmak üzere birkaç yolcu hayatta kalır. Kurtarılmayı beklerken, kısa süre sonra gizemli Yeren\'le karşılaşırlar - Shennongjia dağlarında yüzyıllardır yaşadığı söylenen, yakalanması zor bir maymun-adam yaratık. Acımasız kaçak avcılar Yeren\'i yakalamak için geldiğinde, kahramanlarımız bu eşsiz yaratığın dostları mı yoksa düşmanları mı olduğuna karar vermelidir.', 'Macera', 'Ethan Wiley', 'Chris Walas', 'Sasha Jackson', 'Erroll Shand', 'Douglas Tait', 'Jonathan Kos-Read', 'Lin Hu', '2017', 96, '083. journey-to-the-forbidden-valley-27150.webp', 'https://www.youtube.com/watch?v=IPx3poHSnl0', 5.1, 0),
(84, 'Arrowhead', '', 'Kye, iki ordu arasında kalmış bir savaş esiridir; ikisine de inanmaz. Özgürlük fırsatı sunulduğunda, son bir kurtarma görevine çıkar ve gemisi Arrowhead\'in çakılmasıyla çölde bir ayda mahsur kalır. Kye, inançlarını zorlayacak yeni bir hayat keşfedildiğinde hayatta kalmayı öğrenmek zorundadır.', 'Macera', 'Jesse O\'Brien', 'Jesse O\'Brien', 'Dan Mor', 'Aleisha Rose', 'Shaun Micallef', 'Mark Redpath', 'Christopher Kirby', '2016', 95, '084. ok-ucu-arrowhead-5067.webp', 'https://www.youtube.com/watch?v=mJE5iaIOj1c', 4.4, 0),
(85, 'Beyaz Kuş', 'White Bird', 'R. J. Palacio\'nun Wonder\'daki karakterleri genişleten Auggie and Me adlı çok satan öykü koleksiyonunda, okuyucular Julian\'ın büyükannesi Grandmère ile tanıştırıldı. Palacio, burada Grandmère\'in yürek parçalayıcı öyküsüyle grafik roman çıkışını yapıyor: Genç bir Yahudi kızı olan Palacio\'nun II. Dünya Savaşı sırasında Nazi işgali altındaki bir Fransız köyünde bir aile tarafından nasıl saklandığı; kendisinin ve sınıf arkadaşlarının bir zamanlar dışladığı çocuğun nasıl kurtarıcısı ve en iyi arkadaşı olduğu.', 'Macera', 'Marc Forster', 'Mark Bomback', 'Bryce Gheisar', 'Priya Ghotane', 'Kevan Van Thompson', 'Helen Mirren', 'Laura Hudeckova', '2023', 121, '085. beyaz-kus-white-bird-72234.webp', 'https://www.youtube.com/watch?v=1j0-OBXwS4A', 7.3, 0),
(86, 'Açlık Oyunları: Kuşların ve Yılanların Şarkısı', 'The Hunger Games: The Ballad of Songbirds & Snakes', 'Coriolanus Snow\'un, Panem\'in zalim Başkanı olmasından yıllar önceki hikayesi. Genç, çok kararlı ve Snow ailesi zor zamanlar geçirse de Coriolanus, 10. Açlık Oyunları için akıl hocası olarak seçildiğinde kaderinde bir değişiklik görme şansını yakalar ancak yoksul 12. Bölge\'den Lucy Gray Baird adında bir kız haraççıya akıl hocalığı yapması istendiğinde sevinci yerle bir olur.', 'Macera', 'Francis Lawrence', 'Michael Lesslie', 'Dexter Sol Ansell', 'Rosa Gotzler', 'Clemens Schick', 'Fionnula Flanagan', 'Tom Blyth', '2023', 157, '086. aclik-oyunlari-kuslarin-ve-yilanlarin-sarkisi-the-hunger-games-the-ballad-of-songbirds-snakes-21402.webp', 'https://www.youtube.com/watch?v=RDE6Uz73A7g', 6.7, 0),
(87, 'Kuşatma', 'Asedio', 'Madrid\'in sorunlu bir semtindeki tahliye sırasında Dani, gizli para, polis yolsuzluğu komplosu ve hayatını kurtarmak için dilini bilmediği, hoş karşılanmadığı ve otoritenizin değersiz olduğu düşmanca bir bölgeye kaçmak zorunda kalmasına neden olacak bir suçla karşılaşacaktır.', 'Macera', 'Miguel Ángel Vivas', 'Marta Medina', 'Natalia de Molina', 'Bella Agossou', 'Francisco Reyes', 'Fran Cantos', 'Chani Martín', '2023', 100, '087. kusatma-asedio-16749.webp', 'https://www.youtube.com/watch?v=FkcRmYXoKtM', 5.2, 0),
(88, 'The Wind & the Reckoning', '', 'Cüzzam enfeksiyonları Yerli Hawaii nüfusuna yayılırken, yeni empoze edilen sömürge hükümeti, enfekte olduğundan şüphelenilen tüm Yerli Hawaiililerin Moloka\'i adasına kalıcı olarak sürülmesini emreder. Ancak Ko\'olau (Jason Scott Lee) adlı yerel bir kovboy ve küçük oğlu Kalei (Kahiau Perreira) korkunç hastalığa yakalandıklarında, yetkililere teslim olmayı reddederler ve bu da acımasız beyaz ada yetkilileriyle bir şerifin öldürüldüğü silahlı bir çatışmayı başlatır. Artık avlanan bir adam olan Ko\'olau, ailesiyle birlikte gizli bir vadiye kaçar ve burada başka bir küçük mülteci grubuyla güçlerini birleştirirler. Bir İç Savaş kahramanı tarafından yönetilen bir grup paralı asker tarafından takip edilen kaçaklar, Ko\'olau ve karısı Pi\'ilani\'yi (Lindsay Marie Anuhea Watson) Hawaii tarihinin en destansı olaylarından birine dayanan bir hikayede çağlar boyunca kahraman yapacak son bir çatışma için köşeye sıkıştırılır.', 'Macera', 'David L. Cunningham', 'John Fusco', 'Henry Ian Cusick', 'Johnathon Schaech', 'Jason Scott Lee', 'Sisa Grey', 'Lance Kerwin', '2022', 94, '088. the-wind-the-reckoning-3869.webp', 'https://www.youtube.com/watch?v=pB5kTNJiMM4', 7.3, 0),
(89, 'Ölümcül Çarpışma', 'Hidden Strike', 'İki eski özel kuvvetler askeri, Bağdat\'ın \"Ölüm Otoyolu\" boyunca ilerleyen bir grup sivili, Yeşil Bölge\'nin güvenli alanına ulaştırmak zorundadır.', 'Macera', 'Scott Waugh', 'Arash Amel', 'Jackie Chan', 'John Cena', 'Chunrui Ma', 'Wenli Jiang', 'Jia Xu', '2023', 102, '089. olumcul-carpisma-hidden-strike-87383.webp', 'https://www.youtube.com/watch?v=Kut3nPN04U4', 5.4, 0),
(90, 'Kral Arthur', 'Arthur the King', 'Maceraperest bir yarışçı, destansı bir dayanıklılık yarışına katılması için Arthur adında sokak köpeğini evlat edinir.', 'Macera', 'Simon Cellan Jones', 'Michael Brandt', 'Mark Wahlberg', 'Simu Liu', 'Juliet Rylance', 'Nathalie Emmanuel', 'Ali Suliman', '2024', 107, '090. arthur-the-king-2-20311.webp', 'https://www.youtube.com/watch?v=wjDJNEPghNY', 7, 0),
(91, 'Tatlı Bela', 'Beautiful Disaster', 'Üniversite öğrencileri Abby ve Travis bir süre arkadaş olduktan sonra aşık olurlar. Travis ilişkilere inanmaz, sadece tek gecelik ilişkilere inanır. Ta ki Abby ile tanışana kadar. Bir kitaptan uyarlanan bu film, sorunlu geçmişleri olan iki kişinin birbirlerine güvenmeyi ve olaylara bakış açılarını değiştirmeyi öğrenmesini konu alıyor.', 'Romantik', 'Roger Kumble', 'Roger Kumble', 'Dylan Sprouse', 'Virginia Gardner', 'Austin North', 'Samuel Larsen', 'Neil Bishop', '2023', 96, '091. tatli-bela-beautiful-disaster-92986.webp', 'https://www.youtube.com/watch?v=nvaenzyXl4o', 5.3, 0),
(92, 'O Bana Geldi', 'She Came to Me', 'Besteci Steven Lauddem yaratıcı olarak tıkanmıştır ve büyük geri dönüş operasının müziğini bitirememektedir. Eski terapisti olan karısı Patricia\'nın isteği üzerine ilham arayışına koyulur. Keşfettiği şey, pazarlık ettiğinden veya hayal ettiğinden çok daha fazlasıdır.', 'Romantik', 'Rebecca Miller', 'Rebecca Miller', 'Peter Dinklage', 'Anne Hathaway', 'Marisa Tomei', 'Evan Ellison', 'Harlow Jane', '2023', 102, '092. o-bana-geldi-she-came-to-me-75428.webp', 'https://www.youtube.com/watch?v=ZCbiKiw-Azs', 6, 0),
(93, 'Babasının kızı', 'Jersey Girl', 'Oliver Trinke her zaman Highlands, New Jersey geçmişini geride bırakmaya çalıştı, ancak son altı yıldır bu zordu. Başarılı bir New York City müzik tanıtımcısıydı, ancak karısı Gertrude, kızları Gertie\'yi doğurduktan hemen sonra öldükten sonra, hazırlıksız Ollie, tek bir olayla eğlence-tanıtım sektöründe istenmeyen kişi oldu ve büyük ölçüde bir baba olarak sorumluluklarının önüne profesyonel başarı arzusunu koydu ve Highlands\'e geri döndü ve Gertie ile birlikte ayağa kalkana kadar kendi babası Bart\'ın yanına taşındılar. Bu, Bart ile birlikte Borough of Highlands iş ekibinde yan yana çalışmak anlamına geliyordu, hala yaptığı bir iş. Ayrıca, Gertie\'ye karşı sorumlu ve sevgi dolu bir baba olmayı öğrenmesine rağmen, New York City hayatına ve eğlence tanıtımcısı olarak yüksek rütbeli bir işe geri dönme arzusunu hala taşıyor, Gertie sadece Highlands hayatını biliyor ve babası ve \"Pop\"u Bart dahil her şeyini seviyor. Ollie hayalini gerçekleştirmeye çalışırken, Gertie ile arkadaş olan video mağazasında çalışan ve lisansüstü öğrencisi olan Maya\'nın yardımıyla öncelikleri hakkında daha net bir resim elde edebilir.', 'Romantik', 'Kevin Smith', 'Kevin Smith', 'Betty Aberlin', 'Matt McFarland', 'Sarah Stafford', 'Paulie Litt', 'Christian Fan', '2004', 102, '093. babasinin-kizi-jersey-girl-87772.webp', 'https://www.youtube.com/watch?v=CL04A-DrIEQ', 6.2, 4),
(94, 'Aşk Meşk: Deli Divane', 'Umjolo: The Gone Girl', 'Sevgililer Günü\'nde bir düğünde aşk hayatları kesişen ve hiçbiri kolay kolay unutamayacağı dört kadının hikayesini konu alıyor.', 'Romantik', 'Fikile Mogodi', 'Thuli Zuma', 'Gugu Gumede', 'Tyson Mathonsi', 'Ntando Menzi Ncube', 'Nirvana Nokwe-Mseleku', 'Tina Redman', '2024', 92, '094. ask-mesk-deli-divane-umjolo-the-gone-girl-73980.webp', 'https://www.youtube.com/watch?v=_PUplBYTIMk', 4.4, 0),
(95, 'Fruitcake', '', 'Günümüzün Metro Manila\'sında, kaderleri bir tren yolculuğunda kesişen çeşitli Filipinlilerin hayatlarındaki zorluklarla yüzleşmeleri, birbirine bağlı hikayelerden oluşan yürek ısıtan ve komik bir tabloyu gözler önüne seriyor.', 'Romantik', 'Joel Ferrer', 'Joel Ferrer', 'Joshua Garcia', 'Empoy Marquez', 'Jane Oineza', 'Alex Diaz', 'Markus Paterson', '2024', 97, '095. fruitcake-8147.webp', 'https://www.youtube.com/watch?v=m02xKmGTI3s', 6.1, 0),
(96, 'Head Over Heels', '', 'Addison babasının ayakkabı imalathanesinde yardımcı olur. Kız kardeşiyle birlikte ünlü ayakkabı tasarımcısı Delaney Diaz\'da bir iş için görüşme şansı yakalar. Delaney\'nin pazarlama müdürü olan Austin sayesinde Delaney\'nin asistanı olarak işe girer. Bu zor bir iştir ve Delaney özellikle şirket sıkıntıda olduğu ve işleri yoluna koyacak bir şeye ihtiyaç duyduğu için talepkar bir patrondur. Austin, babasının yönettiği pazarlama şirketi için bir etkinlik planlamaktadır. Addison, Delaney\'yi katılmaya ikna eder çünkü Austin\'in Delaney\'nin tam da ihtiyacı olan şey olabilecek bir sürprizi vardır.', 'Romantik', 'Samantha Wan', 'Christina Brandon-Gómez', 'Rebecca Dalton', 'Olivier Renaud', 'Alexandra Castillo', 'Veronica Hortiguela', 'Michael Dickson', '2024', 84, '096. head-over-heels-61783.webp', 'https://www.youtube.com/watch?v=4eIKmr39f6w', 6.1, 0),
(97, 'Parachute', '', 'Yemek ve beden imajı bağımlılığıyla mücadele ettikten sonra yakın zamanda rehabilitasyondan çıkan Riley\'i takip ediyor. Ethan\'la tanışıyor ve kendini aşk ile yeni bir bağımlılık arasındaki çizgide gezinirken buluyor.', 'Romantik', 'Brittany Snow', 'Becca Gleason', 'Courtney Eaton', 'Thomas Mann', 'Dave Bautista', 'Kid Cudi', 'Francesca Reale', '2023', 108, '097. parasut-parachute-27423.webp', 'https://www.youtube.com/watch?v=4c9VmKpX77Q', 6.2, 0),
(98, 'The Diary of a Teenage Girl', '', '1970\'lerde San Francisco\'da yaşayan genç bir sanatçı olan Minnie, annesinin erkek arkadaşıyla bir ilişkiye başlar. Minnie, çekici olduğunu ve sekse bayıldığını keşfettiğinde zayıf bir öz imaja sahipti. Zaman zaman uyuşturucuya maruz kalmasına rağmen, sanatsal hayal gücü sıklıkla gerçekliğine müdahale eder. Bu hikayede cinsel ihanet ve ergenliğe yeni giren genç bir kız, kendini bir kadın olarak keşfeder.', 'Romantik', 'Marielle Heller', 'Phoebe Gloeckner', 'Bel Powley', 'Willie', 'Kristen Wiig', 'Abby Wait', 'Alexander Skarsgård', '2015', 102, '098. genc-bir-kizin-gunlugu-2565.webp', 'https://www.youtube.com/watch?v=G2M9kqb5wVw', 6.8, 0),
(99, 'First Daughter', '', 'Samantha Mackenzie, ABD Başkanı John Mackenzie ve First Lady Melanie Mackenzie gibi anne ve babasını seviyor ve destekliyor ve Başkan\'ın tek kızı olmanın getirdiği ayrıcalıkların tadını çıkarıyor, ancak bazen \"normal\" olarak gördüğü şey olmak istiyor, yani hayatının dünya tarafından 7/24 incelenmesini istemiyor. Büyük ölçüde Beyaz Saray\'daki hayattan uzaklaşmak ve umarım biraz bağımsızlık iddia etmek için Kaliforniya\'daki Redmond Üniversitesi\'ne gitme kararını verdi, üniversitedeki bu ilk dönemi Başkan Mackenzie\'nin Beyaz Saray\'da ikinci bir dönem için yeniden seçilme teklifiyle aynı zamana denk geldi. Bu nedenle, rakiplerinin aileye daha fazla inceleme yapmak ve onlara karşı her zamankinden daha fazla tehdit oluşturmak da dahil olmak üzere ellerinden gelen her şeyi kullanacaklarını biliyor, bu da daha fazla güvenlik istediği anlamına geliyor. Bu yüzden Sam\'in üniversite deneyimi normalden daha az, onu tehdit edebilecek en küçük şeyleri fark etmek üzere eğitilmiş, çok görünür bir Gizli Servis ajanları ekibi tarafından takip ediliyor. Bu çok görünür ekip, Sam\'in başlangıçta isteksiz olan yurt odası arkadaşı Mia Thompson ile arkadaş edinmesini zorlaştırır. Sam, kendisine izin verilenden daha fazla özgürlük için ailesiyle pazarlık yaparken, ailesine aldırmadan bu özgürlüğü kullanmada Mia ile çoğunlukla işbirlikçi bir suç ortağı bulur. Sam, sonunda yurt danışmanı olduğunu öğrendiği James Lansome şeklinde başka bir sempatik sınıf arkadaşı bulur. James\'in Sam\'e bağımsızlık anlarını bulmasında yardım etmesiyle, Sam ona aşık olur ve James de Sam\'le birlikte. Ancak James, kendi sırlarını saklamaktadır ve bu sırları keşfetmesi durumunda Sam\'in hayatına, üniversite deneyimine ve James\'in kendisine bakış açısını daha da olumsuz etkileyebilir; ki bu sırların seçim tarihi yaklaştıkça daha da olası hale gelmesi muhtemeldir.', 'Romantik', 'Forest Whitaker', 'Jessica Bendinger', 'Katie Holmes', 'Marc Blucas', 'Amerie', 'Michael Keaton', 'Margaret Colin', '2004', 106, '099. baskanin-kizi-first-daughter-3479.webp', 'https://www.youtube.com/watch?v=94LSAoLgBsQ', 5.2, 0),
(100, 'Which Brings Me to You', '', 'İki romantik tükenmişlik bir düğünde tanışır ve frene basmadan önce vestiyerde neredeyse birlikte olurlar. Bunun gerçek olma ihtimaline karşı geçmişleri hakkında samimi itiraflarda bulunmayı kabul ederler.', 'Romantik', 'Peter Hutchings', 'Steve Almond', 'Lucy Hale', 'Nat Wolff', 'John Gallagher Jr.', 'Genevieve Angelson', 'Alexander Hodge', '2023', 98, '100. beni-sana-getiren-yol-which-brings-me-to-you-62907.webp', 'https://www.youtube.com/watch?v=iZphlhww69w', 5.6, 0);

-- --------------------------------------------------------

--
-- Tablo için tablo yapısı `news`
--

DROP TABLE IF EXISTS `news`;
CREATE TABLE IF NOT EXISTS `news` (
  `New_ID` int NOT NULL AUTO_INCREMENT,
  `Movie_ID` int NOT NULL,
  `New_Text` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `New_Title` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `Movie_New_URL` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  PRIMARY KEY (`New_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Tablo için tablo yapısı `personal_access_tokens`
--

DROP TABLE IF EXISTS `personal_access_tokens`;
CREATE TABLE IF NOT EXISTS `personal_access_tokens` (
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `tokenable_type` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `tokenable_id` bigint UNSIGNED NOT NULL,
  `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `token` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `abilities` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `last_used_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `personal_access_tokens_token_unique` (`token`),
  KEY `personal_access_tokens_tokenable_type_tokenable_id_index` (`tokenable_type`,`tokenable_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Tablo için tablo yapısı `users`
--

DROP TABLE IF EXISTS `users`;
CREATE TABLE IF NOT EXISTS `users` (
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `User_Name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `Name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `Phone_Number` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `User_Type_ID` int NOT NULL,
  `User_Password` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `User_Mail` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `google_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `users_user_name_unique` (`User_Name`),
  UNIQUE KEY `users_user_mail_unique` (`User_Mail`),
  UNIQUE KEY `users_google_id_unique` (`google_id`)
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Tablo döküm verisi `users`
--

INSERT INTO `users` (`id`, `User_Name`, `Name`, `Phone_Number`, `User_Type_ID`, `User_Password`, `User_Mail`, `created_at`, `updated_at`, `google_id`) VALUES
(1, 'deneme', 'deneme', '05444295818', 1, '$2y$10$Bl2VmLImrkQ1WBsZ2V859uT7LdqHPdRGv.TIypgkLc3NPpOI.tAJC', 'deneme@gmil.com', '2025-01-14 08:35:17', '2025-01-14 08:35:17', NULL),
(2, 'ppp', 'ppp', '05444295818', 1, '$2y$10$LgrRaiaAPgtZJhFeqG0NvunasErs5ENARpv7OLE2rM2PzofSHWDee', 'aghsda@gmail.com', '2025-01-14 08:38:55', '2025-01-14 08:38:55', NULL),
(3, 'asdasd', 'asdasd', '54568465', 1, '$2y$10$4xD/n2cicw91cHB6o3eNPuuX5JRJMzOEEsqdbdjdQdFSO9SPqyYDu', 'hasjdas@gmail.com', '2025-01-14 08:41:43', '2025-01-14 08:41:43', NULL),
(4, 'oooo', 'asdasdas', '54261', 1, '$2y$10$F6axuTm.ZAeUPQYJD7xCuubTjBntqcFu8/ggVnSuYOUQv6BVk78Lq', 'adahsd@gmail.com', '2025-01-14 08:44:28', '2025-01-14 08:44:28', NULL),
(5, 'merhaba', 'merhaba', '0539196147', 1, '$2y$10$2ffH6QdyKz5kUuoyIlgYvea.0ofCvRTZo3nUWf89auMhhzRCI7sGG', 'deneme1@gmail.com', '2025-01-14 09:13:31', '2025-01-14 09:13:31', NULL),
(6, 'irfan', 'irfan', '8901233212', 1, '$2y$10$ho638TAdYVdvp2iN5743M.0Egy4jZIsYfnItqTgSnTx0ZzJaSw81q', 'irfan@gmail.com', '2025-01-23 11:36:13', '2025-01-23 11:36:13', NULL),
(7, 'mehmet', 'mehmet', '1231232334', 1, '$2y$10$0xz.DL9A8m978YSWfGG4XO4BA.Q24.IjIHF.bFU2hVzzbZGa2Q0wC', 'has@gmail.com', '2025-01-23 11:42:34', '2025-01-23 11:42:34', NULL),
(8, 'habip', 'habip', '05369859', 1, '$2y$10$5eAJIAKzlorlNG5Nxleq7eoJmbfazu.OYBTzsYr5BctQNmC/D5nui', 'merhabalar@gmail.com', '2025-01-25 06:47:24', '2025-01-25 06:47:24', NULL),
(9, 'habip123', 'asdasd', '6515685', 1, '$2y$10$EPj3KfFO7YwITLblJ/YwKOSVkPAIjlX/iaqkXvbNZs1f9Nf/z/8aq', 'merhaba@gmail.com', '2025-01-25 06:49:03', '2025-01-25 06:49:03', NULL),
(10, '12316a', 'merhabalaıjduqıwund', '8276526', 1, '$2y$10$vDifD4DAtmEMenPBWtvrnOAaowb/mMNXWLqhdGo5M02iPgPF860RK', 'ajksd@gmail.com', '2025-01-25 06:51:50', '2025-01-25 06:51:50', NULL),
(11, 'admin', 'filmology', '1111111111111', 1, '$2y$10$V10YQsGqvpuYaVFiDHkvDeq1xqqMcBKqG/oJMrAUB3Pzk7RJighoC', '132@gmail.com', '2025-01-25 08:50:52', '2025-01-25 08:50:52', NULL),
(12, 'deneme12', 'ömer', '053288895', 1, '$2y$10$oRoQaY9tBzifvJcDHsAuGe6vE668ES0DFcdmr4dzsTFClhNf4ckuy', 'öçöö@gmail.com', '2025-01-26 02:47:23', '2025-01-26 02:47:23', NULL),
(13, 'selim', 'selim', '5641861489485', 1, '$2y$10$gQJqX6YxotF3jL2/5is8S.BTZyBDJAHXwfKzXKIckmAHO6O9wl6jq', 'ahsdahsq@gmail.com', '2025-01-26 10:31:18', '2025-01-26 10:31:18', NULL),
(14, 'selimknc', 'Selim Köneçoğlu', '5398784514', 1, '$2y$10$g5L9cyp2OB8.9PBz49KzzeNukZNZqlx/bGpGyZ424kdq6anzsN4sG', 'selim@test.com', '2025-01-26 11:04:28', '2025-01-26 11:04:28', NULL),
(15, 'ferit', 'Ferit', '55487841514454', 1, '$2y$10$NX4.C3uI4v/w5b5Fdt9roOOZwVFBo4DzrKYj2MxAq3w2bxDpJtLRu', 'merhaba1@gmail.com', '2025-01-26 11:27:51', '2025-01-26 11:27:51', NULL);

-- --------------------------------------------------------

--
-- Tablo için tablo yapısı `user_types`
--

DROP TABLE IF EXISTS `user_types`;
CREATE TABLE IF NOT EXISTS `user_types` (
  `User_Type_ID` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `User_Type` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  PRIMARY KEY (`User_Type_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
